### ISSUE TITLE
File path points to root directory of sender

### ISSUE THREAD

**Issue by naspy971** [dustin10/VichUploaderBundle#1008]
Hello,

I'm using this bundle with EasyAdmin on Symfony 4, and I try to upload a user profile picture, so I followed all the instructions of the documentation, but when I upload the image, I get something like this : 

`/Users/naspy/Symfony/symlar2-back/public/uploads/users/profile picture/5cfd306bf0e6d780054567.jpg`

While I need to store only the path after **public/** like this : 
``/uploads/users/profile picture/5cfd306bf0e6d780054567.jpg``

Here's my vich_uploader.yaml config so far : 

```
vich_uploader:
  db_driver: orm
  mappings:
    users_profile_picture:
#      uri_prefix:         '%app.path.users_profile_picture%'
      upload_destination: '%kernel.project_dir%/public%app.path.users_profile_picture%'
      namer: Vich\UploaderBundle\Naming\UniqidNamer
```

Here's my services.yaml config : 

```
parameters:
    app.path.users_profile_picture: /uploads/users/profile-picture
```

I guess the "issue" comes from the kernel.project_dir but I can't take it off without error.

Thanks

**Comment by garak** [comment]
Uncomment `uri_prefix`

**Comment by naspy971** [comment]
Now it doesnt upload the image at all, anyway I figured this out : 

```
vich_uploader:
  db_driver: orm
  mappings:
    users_profile_picture:
      upload_destination: '%app.path.users_profile_picture%'
      namer: Vich\UploaderBundle\Naming\UniqidNamer
```

```
parameters:
    app.path.users_profile_picture: uploads/users/profile-picture
```

And it works now.
