### ISSUE TITLE
Unable to edit user with image from EasyAdmin

### ISSUE THREAD

**Issue by naspy971** [dustin10/VichUploaderBundle#1010]
Hello,

I've set up VichUploaderBundle so I can upload Users profile picture from within EadyAdmin panel.

I followed this tutorial : https://symfony.com/doc/master/bundles/EasyAdminBundle/integration/vichuploaderbundle.html

I'm able to upload an image when creating a user.

My issue comes when I try to edit a user that has a profile picture, when I click on "edit" action, I get this error : 

`The form's view data is expected to be an instance of class Symfony\Component\HttpFoundation\File\File, but is a(n) string. You can avoid this error by setting the "data_class" option to null or by adding a view transformer that transforms a(n) string to an instance of Symfony\Component\HttpFoundation\File\File.`

So I tried this : 

```
    form:
        fields:
        - { property: 'firstname', label: 'Prénom' }
        - { property: 'lastname', label: 'Nom' }
        - { property: 'email', label: 'Email' }
        - { property: 'profilePictureFile', label: 'Photo', type: 'vich_image' }
      edit:
        form_options: { data_class: null }
```

But I get this error instead : 

`Cannot read index "firstname" from object of type "App\Entity\User" because it doesn't implement \ArrayAccess.`

Same if I change the type from 'vich_image' to 'file'.

In this tutorial : https://symfony.com/doc/current/controller/upload_file.html they say this : 

<img width="698" alt="Capture d’écran 2019-06-14 à 14 46 00" src="https://user-images.githubusercontent.com/25461579/59510512-28b94a00-8eb4-11e9-87ab-defe7b42c4d1.png">

So I guess I might have to modify the edit form from within the UserController like this : 

```
public function createEditForm($entity, $view)
    {
        $formBuilder = parent::createEditForm($entity, $view);
        dd($formBuilder);
    }
```
But I can't even get to the die dump, I get the same error ( the first one ).

If I die dump before calling the `parent::createEditForm`, the dd works.

I'm really confused right now and still unable to find a solution to this problem.

Please help, thanks.
