### ISSUE TITLE
Deprecation private service in Symfony 3.4

### ISSUE THREAD

**Issue by VincentLanglet** [dustin10/VichUploaderBundle#1012]
|    Q        |   A
|------------ | -----
| Version     | 1.9.2

### Support Question

I try to update to symfony 4, so I have to get rid of all the deprecations message and I get this one from `VichUploadBundle`:
```
User Deprecated: The "AssuranceVie\Service\Namer.document" service is private, getting it from the container is deprecated since Symfony 3.2 and will fail in 4.0. You should either make the service public, or stop using the container directly and use dependency injection instead.
```

My service is public, but it's seems to be useless because this bundle create a new service called AssuranceVie\Service\Namer.document.

I look at the code, and I think it's coming from this function
```php
class VichUploaderExtension extends Extension 
{
...

protected function createNamerService(ContainerBuilder $container, string $mappingName, array $mapping): array
    {
        $serviceId = \sprintf('%s.%s', $mapping['namer']['service'], $mappingName);
        $container->setDefinition(
            $serviceId, new ChildDefinition($mapping['namer']['service'])
        );

        $mapping['namer']['service'] = $serviceId;

        return $mapping;
    }
```

In symfony code, `ChildDefinition` is private ; cf `__construct`
```php
class ChildDefinition extends Definition
{
    private $parent;

    /**
     * @param string $parent The id of Definition instance to decorate
     */
    public function __construct($parent)
    {
        $this->parent = $parent;
        $this->setPrivate(false);
    }
```

A solution can be 
```php
$service = new ChildDefinition($mapping['namer']['service']);
$service->setPublic(true);
$container->setDefinition($serviceId, $service);
```

There is the same, in `createListener`.

**Comment by garak** [comment]
How are you trying to get such service?

**Comment by VincentLanglet** [comment]
@garak I don't
I believe the call is made in the VichUploaderBundle.

I forgot to add my config:
```yml
vich_uploader:
    db_driver: orm
    storage: gaufrette
    mappings:
        voucher:
            inject_on_load: true
            uri_prefix: "%aws_base_url%/%aws_bucket%/voucher"
            namer: 'AssuranceVie\Service\AsciiNamer'
            upload_destination: voucher_fs
            delete_on_update: false
            delete_on_remove: false
        ...
        document:
            inject_on_load: true
            uri_prefix: "%aws_private_base_url%/%aws_private_bucket%/subscription"
            namer: 'AssuranceVie\Service\Namer'
            upload_destination: document_fs
            delete_on_update: false
            delete_on_remove: false
```
I use my custom Namer
