### ISSUE TITLE
Support the official Flysystem Bundle

### ISSUE THREAD

**Issue by ThomasBerends** [dustin10/VichUploaderBundle#1015]
### Feature Request

|    Q        |   A
|------------ | ------
| New Feature | yes
| RFC         | no
| BC Break    | maybe?

#### Summary

Recently, the PHP League made their official Flysystem Bundle for Symfony public. I think it would be great if VichUploaderBundle would support this bundle.
https://github.com/thephpleague/flysystem-bundle

To keep backwards compatibility, and since 'flysystem' for the 'storage' configuration option is taken, an alternative could be used like 'flysystem_bundle'.

**Comment by garak** [comment]
It looks like bundle supports only Symfony 4.2 and above, while this bundle supports Symfony >= 3.4

**Comment by garak** [comment]
Taking a closer look, I don't see a reason that's stopping you from using the new flysystem-bundle.
The only point we can change is [documentation](https://github.com/dustin10/VichUploaderBundle/blob/master/Resources/doc/storage/flysystem.md), for which you're free to open a PR

**Comment by ThomasBerends** [comment]
Okay, time for a challenge then. Time to get this working. I'm having an error though, and it seems to be coming from VichUploaderBundle:

`The service "vich_uploader.storage.flysystem" has a dependency on a non-existent service "oneup_flysystem.mount_manager".  `

I've looked around, and I currently do not see a way around this.

**Comment by Livda** [comment]
Hi guys, I've found a work-around to use this bundle with the last version of Flysystem bundle. You just have to manually link all the filesystems created inside the MountManager :

```yaml
flysystem:
    storages:
        user.storage:
            adapter: 'local'
            options:
                directory: '%kernel.project_dir%/var/storage/user'
        admin.storage:
            adapter: 'local'
            options:
                directory: '%kernel.project_dir%/var/storage/admin'
        cache.storage:
            adapter: 'local'
            options:
                directory: '%kernel.project_dir%/var/storage/cache'

services:
    League\Flysystem\MountManager:
        arguments:
            -
                user: '@user.storage'
                admin: '@admin.storage'
                cache: '@cache.storage'
        public: false

    oneup_flysystem.mount_manager:
        alias: League\Flysystem\MountManager
        public: true

vich_uploader:
    db_driver: orm
    storage: 'flysystem'

    mappings:
        user_images:
            uri_prefix: /users/images
            upload_destination: 'user'
        admin_images:
            uri_prefix: /admin/images
            upload_destination: 'admin'
        cache_images:
            uri_prefix: /cache/images
            upload_destination: 'cache'
```
