### ISSUE TITLE
Custom storage is not found because of strtolower

### ISSUE THREAD

**Issue by VincentLanglet** [dustin10/VichUploaderBundle#1024]
### Bug Report

|    Q        |   A
|------------ | ------
| BC Break    | ?
| Version     | 1.9.*

#### Summary

Since there is a normalisation for the storage
```
->beforeNormalization()
    ->ifString()
    ->then(function ($v) {
        return \strtolower($v);
    })
 ->end()
```

This config does not work
```
vich_uploader:
    db_driver: orm
    storage: '@App\Service\VichUploader\Storage'
```
You receive the message "assurancevie\service\vichuploader\storage is not found".

Actual workaroung
```
services:
    vich_uploader_custom_storage: '@App\Service\VichUploader\Storage'

vich_uploader:
    db_driver: orm
    storage: '@vich_uploader_custom_storage'
```
