### ISSUE TITLE
Extension ".0" is disregarded when naming files

### ISSUE THREAD

**Issue by tantegerda1** [dustin10/VichUploaderBundle#1030]
### Bug Report

|    Q        |   A
|------------ | ------
| BC Break    | no
| Version     | 1.10.1

#### Summary

When uploading files with an `.0` extension, the available namers ignore the extension and rename the file as if it had no extension at all or based on a mime-type guess.

#### Current behavior

new file name `5d6faa6b945d0819644602` (using UniqidNamer as example)

#### How to reproduce

Use this mapping:

```
vich_uploader:
    # ...
    mappings:
        product_image:
            upload_destination: product_image_fs
            namer: Vich\UploaderBundle\Naming\UniqueNamer
```
Upload a file `examplefile.0` as product_image.

Failing unit tests are provided by 6ebc7af29c50b07beca01148cfe51e0cfcfcdfeb .

#### Expected behavior

new file name `5d6faa6b945d0819644602.0`
