### ISSUE TITLE
Old image won't delete after update

### ISSUE THREAD

**Issue by tv78-coder** [dustin10/VichUploaderBundle#1035]
|    Q        |   A
|------------ | -----
| Version     | ^1.10

### Support Question

Hello. This might be a very old question, but i still have no idea how to solve it.

I have a problem that the old image is still in the folder even i upload a new one to my entity. My entity imageName is update according to the new upload. But i want to delete the old one when i upload new one.

I'm using UploadHandler to upload my image (not symfony form)

```
public function uploadImage(Request $request, UploadHandler $uploadHandler) {
     $file = $request->files->get('imageFile');
     $staff->setImageFile($file);
     $uploadHandler->upload($staff, 'imageFile');
}
```

I've tried to write `delete_on_update: true` in my vich_uploader.yaml but it is not working.

```
mappings:
        staff_image:
            uri_prefix: '/images/staff'
            upload_destination: '%kernel.project_dir%/public/images/staff'
            namer: Vich\UploaderBundle\Naming\OrignameNamer

            delete_on_update: true
```
