### ISSUE TITLE
DirectoryNamer has to be public?

### ISSUE THREAD

**Issue by Steveb-p** [dustin10/VichUploaderBundle#1040]
|    Q        |   A
|------------ | -----
| Version     | 1.8.8

### Support Question

https://github.com/dustin10/VichUploaderBundle/blob/master/Resources/doc/directory_namer/howto/create_a_custom_directory_namer.md shows how to implement custom directory namer, but it seems that it has to be `public` in container. Is it simply a matter of missing note in documentation, or am I doing something wrong in my configuration?

Configuration I'm using for reference:
```yaml
vich_uploader:
    db_driver: orm

    templating: false
    twig: false
    form: false

    mappings:
        creation_file:
            directory_namer: App\Util\CreationFileDirectoryNamer
            uri_prefix: /content/creation-files
            upload_destination: '%kernel.project_dir%/public/content/creation-files'

```
