### ISSUE TITLE
On UPLOAD, Entity gets hydrated but file is not uploaded with manual upload.

### ISSUE THREAD

**Issue by MilesYM** [dustin10/VichUploaderBundle#1072]
|    Q        |   A
|------------ | -----
| Latest     | x.y.z

### Support Question

I am trying to set up a form to upload a file with VichUploader & axios/ajax.

The form I am sending looks like this on the console:
https://i.stack.imgur.com/QymNc.png

I have set up vich uploader and GNP properly as the form works in non-ajax forms.

I have a simple file to upload with an Entity set like the following:

    <?php
    
    namespace App\Entity;
    
    use Doctrine\ORM\Mapping as ORM;
    use Symfony\Component\HttpFoundation\File\File;
    use Symfony\Component\HttpFoundation\File\UploadedFile;
    use Vich\UploaderBundle\Mapping\Annotation as Vich;
    
    /**
     * Class Logo
     *
     * @ORM\Table(name="logos")
     * @ORM\Entity()
     * @Vich\Uploadable()
     */
    class Logo
    {
        /**
         * @var int
         *
         * @ORM\Column(type="integer", name="id")
         * @ORM\Id
         * @ORM\GeneratedValue(strategy="AUTO")
         */
        private $id;
    
        /**
         * @var string
         *
         * @ORM\Column(type="string", length=255, nullable=true)
         */
        private $logoName;
    
        /**
         * NOTE: This is not a mapped field of entity metadata, just a simple property.
         *
         * @var File
         *
         * @Vich\UploadableField(mapping="logo", fileNameProperty="logoName", size="logoSize")
         */
        private $logoFile;
    
        /**
         * @ORM\Column(type="integer", nullable=true)
         *
         * @var integer
         */
        private $logoSize;
    
        /**
         * @ORM\Column(type="datetime", nullable=true)
         */
        private $updatedAt;

The getters and setters are exactly like [on the documentation][2]

I am doing a manula upload here but nothing gets uploaded on my AWS S3 bucket:

        /**
         * Update a Logo for the Startup
         *
         * @Rest\Post("/logo")
         *
         * @param Request $request
         * @param UserRepository $userRepository
         *
         * @return Response
         */
        public function updateLogo(Request $request, UserRepository $userRepository): Response
        {
            $success = false;
    
            // Retrieve the user
            $user = $this->getUser();

            $image = $request->files->get('logoFile');

            if(!$image instanceof UploadedFile) {
                throw new HttpException(400, "Cannot find a file to upload. Try again.");
            }

        //$image is now an instance of Symfony\Component\HttpFoundation\File\UploadedFile
    
            $startup = $user->getStartup();
    
    
            $logo = new Logo();
           
    
                //Initialize EntityManager to update the user
                $entityManager = $this->getDoctrine()->getManager();
    
                $logo->setLogoFile($image);
                $startup->setLogo($logo);
    
                try {
                    $entityManager->persist($startup);
                    $entityManager->flush();
                } catch (ORMException $e) {
                    throw new HttpException(500, "Couldn't update your profile. Try again.");
                }
    
                $success = true;
            }
    
            $view = $this->view($success, 200);
    
            return $this->handleView($view);
        }

When doing this, it does create a new object Logo but and all the fields are correct but no file is uploaded to AWS S3. 

Not sure what is happening under the hood. What Am I missing?

Thank you very much.

  [2]: https://github.com/dustin10/VichUploaderBundle/blob/master/docs/usage.md

**Comment by garak** [comment]
I think your should avoid bypassing form, so try to not use directly Request and follow usual path: bind your form with Request and get values (including files) from your form.
Also, reducing the scope will help: try to get it working on local filesystem, then go to see if it works on AWS.

**Comment by MilesYM** [comment]
Thank you Garak for your help.

I have rewritten mon controller the following way and have the same result. The entity gets hydrated but the file isn't uploaded.

Controller:
```
public function updateLogo(Request $request, UserRepository $userRepository): Response
    {
        $success = false;

        // Retrieve the user
        $user = $this->getUser();
        $image = $request->files->get('logoFile');

        if(!$image instanceof UploadedFile) {
            throw new HttpException(400, "Cannot find a file to upload. Try again.");
        }
        //$image is now an instance of Symfony\Component\HttpFoundation\File\UploadedFile

        $startup = $user->getStartup();

        $logo = new Logo();
        $form = $this->createForm(LogoType::class, $logo);
        $form->handleRequest($request);

        //Initialize EntityManager to update the user
        $entityManager = $this->getDoctrine()->getManager();

        $logo = $form->getData();
        $logo->setLogoFile($image);
        $startup->setLogo($logo);

        try {
            $entityManager->persist($logo);
            $entityManager->persist($startup);
            $entityManager->flush();
        } catch (ORMException $e) {
            throw new HttpException(500, "Couldn't update your profile. Try again.");
        }

        $success = true;

        $view = $this->view($success, 200);

        return $this->handleView($view);
    }
```

Here is my LogoType:

```
<?php

// src/Form/UserType.php
namespace App\Form;

use App\Entity\Logo;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;

use Symfony\Component\OptionsResolver\OptionsResolver;
use Vich\UploaderBundle\Form\Type\VichFileType;

class LogoType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        // Remember username is email
        $builder
            ->add('logoFile', VichFileType::class, [
                'label'         => false,
                'required'      => true,
                'allow_delete'  => false,
                'download_uri'  => true,
                'download_label' => true,
                'download_link' => true,
            ])
        ;
    }

    public function configureOptions(OptionsResolver $resolver)
    {
        $resolver->setDefaults(array(
            'data_class' => Logo::class,
            'csrf_protection' => false,
        ));
    }
}
```

And my config files:
```
knp_gaufrette:
    stream_wrapper: ~
    adapters:
        document_adapter:
            aws_s3:
                service_id: 'ct_file_store.s3'
                bucket_name: '%env(AWS_PRIVATE_BUCKET_NAME)%'
                detect_content_type: true
                options:
                    create: true
                    directory: 'decks'
        logo_adapter:
            aws_s3:
                service_id: 'ct_file_store.s3'
                bucket_name: '%env(AWS_PRIVATE_BUCKET_NAME)%'
                detect_content_type: true
                options:
                    create: true
                    directory: 'logos'
        userpic_adapter:
            aws_s3:
                service_id: 'ct_file_store.s3'
                bucket_name: '%env(AWS_PUBLIC_BUCKET_NAME)%'
                detect_content_type: true
                options:
                    create: true
                    directory: 'investors'
    filesystems:
        document_fs:
            adapter: document_adapter
        userpic_fs:
            adapter: userpic_adapter
        logo_fs:
            adapter: logo_adapter
```

```
vich_uploader:
    db_driver: orm
    mappings:
        document:
            inject_on_load: false
            uri_prefix: "%env(AWS_BASE_URL)%/%env(AWS_PRIVATE_BUCKET_NAME)%/decks"
            upload_destination: document_fs
            delete_on_update: true
            delete_on_remove: true
            namer:
                service: vich_uploader.namer_origname
        userpic:
            inject_on_load: false
            uri_prefix: "%env(AWS_BASE_URL)%/%env(AWS_PUBLIC_BUCKET_NAME)%/investors"
            upload_destination: userpic_fs
            delete_on_update: true
            delete_on_remove: true
            namer:
                service: vich_uploader.namer_origname
        logo:
            inject_on_load: false
            uri_prefix: "%env(AWS_BASE_URL)%/%env(AWS_PUBLIC_BUCKET_NAME)%/logos"
            upload_destination: logo_fs
            delete_on_update: true
            delete_on_remove: true
            namer:
                service: vich_uploader.namer_origname
```

Note that document is working fine with a normal http symfony form.
Any help is much welcome.

Thank you
