### ISSUE TITLE
How do I get the image url when retrieving from database?

### ISSUE THREAD

**Issue by gundamftw** [dustin10/VichUploaderBundle#1075]
I am using Symfony 5, I have successfully uploaded the image files and stored the file names into the database using the bundle, but now I have trouble getting the url to display them. I want to get only the uri to the file, not full path, like this `www.abc.com/img` instead of `www.abc.com/img/1.jpg` 

my setting in yaml file:
```
vich_uploader:
    db_driver: orm

    mappings:
        image:
            uri_prefix: /img
            upload_destination: '%kernel.project_dir%/public/images
```

controller:
```
public function index(UploaderHelper $helper)
{
    $image = new Image(); // Image entity
    $path = $helper->asset($image , 'imageFile');

    var_dump($path );
}
```

I followed the instruction from the doc, passing in the image entity and imageFile to the helper function, but var_dump gives me a "NULL" value, no path.
