### ISSUE TITLE
uri_prefix is not working as expected when using Flysystem

### ISSUE THREAD

**Issue by liweiyi88** [dustin10/VichUploaderBundle#1089]
### Bug Report

|    Q        |   A
|------------ | ------
| BC Break    | no
| Version     | 1.13.0

#### Summary
Symfony version: 4.4

#### Expected behavior

Following the config shown in the [doc](https://github.com/dustin10/VichUploaderBundle/blob/master/docs/storage/flysystem.md), I should be able to upload a file to the `/images/products/` "directory" in  the cloud storage with the config below.
```
vich_uploader:
    db_driver: orm
    storage: flysystem

    mappings:
        media_object:
            uri_prefix: '/images/products'
            upload_destination: users.image.storage
```

#### Current behavior

The file is uploaded to the root directory.

#### The solution and question
As there is no directory namer in the config, this [line](https://github.com/dustin10/VichUploaderBundle/blob/master/src/Storage/AbstractStorage.php#L48) in the code returns "" as the dir, so the config described in above won't work.

The workaround I made is to create a custom DirectoryNamer:
```
<?php

declare(strict_types=1);

namespace App\Bridge\VichUploader;

use Vich\UploaderBundle\Mapping\PropertyMapping;
use Vich\UploaderBundle\Naming\DirectoryNamerInterface;

final class UriPrefixDirectoryNamer implements DirectoryNamerInterface
{
    public function directoryName($object, PropertyMapping $mapping): string
    {
        return $mapping->getUriPrefix();
    }
}
```
and add `directory_namer: App\Bridge\VichUploader\UriPrefixDirectoryNamer` in the config.

So, my question is: should we update the doc to mention the issue or implement a default directory namer as above?

**Comment by liweiyi88** [comment]
By the way, with above changes, it breaks the `resolveUri` function as `uri_prefix` is prefixed to the final uri.

**Comment by garak** [comment]
I'm not so much into Flysystem, maybe @tgalopin can bring some help here

**Comment by liweiyi88** [comment]
There are two options to resolve the issue.
1. Advising user to create custom cloud directory namer by the following steps:
```
// vich_uploader.yaml
vich_uploader:
    db_driver: orm
    storage: flysystem

    mappings:
        media_object:
            uri_prefix: '' # this is necessary as it will use /upload/ as the default uri prefix.
            upload_destination: users.image.storage
            namer: Vich\UploaderBundle\Naming\Base64Namer
            directory_namer: App\Bridge\VichUploader\CloudDirectoryNamer
```
```
// custom directory namer
<?php

declare(strict_types=1);

namespace App\Bridge\VichUploader;

use Vich\UploaderBundle\Mapping\PropertyMapping;
use Vich\UploaderBundle\Naming\DirectoryNamerInterface;

final class CloudDirectoryNamer implements DirectoryNamerInterface
{
    public function directoryName($object, PropertyMapping $mapping): string
    {
        // Do not prefix the dir with "/" as vich upload will prefix "/".
        return 'images/products/' ;
    }
}
```
```
//services.yaml
 ...
  App\Bridge\VichUploader\CloudDirectoryNamer:
        public: true
```
With these changes, we don't need to update the code of this bundle, instead, update the doc to advise user to create a custom directory namer (or maybe we create this cloud directory namer in the bundle itself).

2. Update the `getUploadDir` method of  `PropertyMapping` to take the uri prefix into consideration when get the dir and also update `resolveUri` method of `AbstractStorage` to get rid of the `$mapping->getUriPrefix()` when necessary.

I wonder 2. will introduce BC for existing users even though it is a fix in the codebase and improve UX as ppl won't need to create custom directory namer.

What do you think?

**Comment by tgalopin** [comment]
We should have the same behavior on both Flysystem bundles: this is a bug from my implementation. I'll have a look.

**Comment by liweiyi88** [comment]
Awesome, thanks @tgalopin

**Comment by tgalopin** [comment]
I did some research and realized something: uri_prefix is not meant to add a prefix to the *uploaded file path* but to add a prefix to the *web path to that directory*. I don't use this bundle personally so I'm not sure precisely how this is supposed to work, but I would suggest to use the Flysystem prefix feature instead:

```
# config/packages/flysystem.yaml

flysystem:
    storages:
        users.storage:
            adapter: 'aws'
            options:
                client: 'aws_client_service' # The service ID of the Aws\S3\S3Client instance
                bucket: 'bucket_name'
                prefix: 'optional/path/prefix'
```

https://github.com/thephpleague/flysystem-bundle/blob/master/docs/2-cloud-storage-providers.md#aws-s3
