### ISSUE TITLE
Unable to get filename property value: "image" (Can't get URLs for uploaded assets)

### ISSUE THREAD

**Issue by gavD** [dustin10/VichUploaderBundle#109]
Hi,

I ran the following in a controller:

```
    $entity = $this->getSupportingDocumentPack();// get the entity..
    $helper = $this->container->get('vich_uploader.templating.helper.uploader_helper');
    print_r($entity->getImage());die;
```

and it echoes:

```
    Symfony\Component\HttpFoundation\File\File Object ( [pathName:SplFileInfo:private] => gaufrette://on_disk_fs/5101404fe2e8d.jpeg [fileName:SplFileInfo:private] => 5101404fe2e8d.jpeg )
```

So this looks fine to me. If I then run:

```
  $path = $helper->asset($entity, 'image');
```

I get:

```
 Unable to get filename property value: "image"
```

I went back to the drawing board and copied and pasted the example code from https://github.com/dustin10/VichUploaderBundle/blob/master/Resources/doc/index.md but to no avail. 

Here is my config.yml:

```
knp_gaufrette:
  adapters:
      on_disk_adapter:
        local:
            directory: "%filepath_disk%"
  filesystems:
    on_disk_fs:
        adapter:    on_disk_adapter

vich_uploader:
    db_driver: orm
    gaufrette: true
    storage: vich_uploader.storage.gaufrette
    mappings:
        product_image:
            upload_destination: on_disk_fs
            namer: vich_uploader.namer_uniqid
            delete_on_update: true
```

I would appreciate any help!

Thanks,
- Gavin
