### ISSUE TITLE
Regression for resolvePath in version 1.10.2

### ISSUE THREAD

**Issue by tristanbes** [dustin10/VichUploaderBundle#1099]
### BC Break Report

|    Q        |   A
|------------ | ------
| BC Break    | yes
| Version     | 1.10.2

#### Summary

Regression happened in `1.10.2`
https://github.com/dustin10/VichUploaderBundle/compare/1.10.1...1.10.2

#### Previous behavior

v1.10.1:  
```php
<?php

declare(strict_types=1);

namespace App\EventListener;

use App\Entity\Media;
use Doctrine\Common\EventSubscriber;
use Doctrine\ORM\Event\LifecycleEventArgs;
use Doctrine\ORM\Events;
use Liip\ImagineBundle\Imagine\Cache\CacheManager as LiipCacheManager;
use Vich\UploaderBundle\Storage\StorageInterface;

class MediaSubscriber implements EventSubscriber
{
    private $storage;
    private $liipCacheManager;

    public function __construct(StorageInterface $storage, LiipCacheManager $liipCacheManager)
    {
        $this->storage          = $storage;
        $this->liipCacheManager = $liipCacheManager;
    }

    public function getSubscribedEvents()
    {
        return [
            Events::postLoad,
        ];
    }

    public function postLoad(LifecycleEventArgs $args): void
    {
        $media = $args->getEntity();

        if (!$media instanceof Media) {
            return;
        }

        $this->computeMediaContentUrl($media);
    }

    protected function computeMediaContentUrl(Media $media): void
    {
        try {
            if (null === $path = $this->storage->resolvePath($media, 'file')) {
                throw new \RuntimeException(sprintf(
                    'Generated path for Media#%d can not be null.',
                    $media->getId()
                ));
            }

            var_dump($path);

            $path = $this->liipCacheManager->getBrowserPath($path, 'original');

            $media->setContentUrl($path);
        } catch (\Exception $e) {
        }
    }
}
```
```php
// Media.php
    /**
     * @var File|null
     * @Assert\NotNull(groups={"create"})
     * @Vich\UploadableField(mapping="medias", fileNameProperty="filePath")
     */
    public $file;
```

returns  `string(31) "test-5e39ac752de03261084462.png"`

We upload the media through API Platform, though I did not share the `@ApiResource` associated with it.

#### Current behavior

`>= v1.12.0`:

```php
$this->storage->resolvePath($media, 'file')
```
returns  `string(62) "/srv/app/public/uploads/medias/test-5e39ad2f1930a768840448.png"`

#### How to reproduce

```yml
oneup_flysystem:
    adapters:
        default_adapter:
            local:
                directory: '%kernel.project_dir%/public//uploads/medias'
    filesystems:
        default_filesystem:
            adapter: default_adapter
            mount: default_filesystem

vich_uploader:
    db_driver: orm
    storage: flysystem

    mappings:
        medias:
            uri_prefix: '/uploads/medias'
            upload_destination: default_filesystem
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
            delete_on_remove: true

```

I can't find any guide to fix this issue inside: https://github.com/dustin10/VichUploaderBundle/blob/master/UPGRADE.md

Thank you.

**Comment by garak** [comment]
We had a troublesome history with Flysystem, unfortunately I had some difficulties trying to follow it (since I don't use Flystem myself).
You can see for example issue #1089 and PR #1092
Can you please try with latest `master`? You can use our alias (anyway, a new version is planned to be released this week)

**Comment by tristanbes** [comment]
Hello,

So I tried with dev-master: the issue is still ongoing;

I tried both solution given in #1089 but they are not working, I still got 
`/srv/app/public/uploads/medias/test-5e39ad2f1930a768840448.png`
instead of 
`/uploads/medias/...`

What I tried:

```php
<?php

declare(strict_types=1);

namespace App\Bridge\VichUploader;

use Vich\UploaderBundle\Mapping\PropertyMapping;
use Vich\UploaderBundle\Naming\DirectoryNamerInterface;

final class MediaDirectoryNamer implements DirectoryNamerInterface
{
    private $mediaPath;

    public function __construct(string $mediaPath)
    {
        $this->mediaPath = $mediaPath;
    }

    public function directoryName($object, PropertyMapping $mapping): string
    {
        // Do not prefix the dir with "/" as vich upload will prefix "/".
        return $this->mediaPath;
    }
}
```

```yml
    App\Bridge\VichUploader\MediaDirectoryNamer:
        public: true
        arguments:
            $mediaPath: 'uploads/medias'
```
```yml
vich_uploader:
    db_driver: orm
    storage: flysystem

    mappings:
        medias:
            uri_prefix: '' # this is necessary as it will use /upload/ as the default uri prefix if not set the value here.
            upload_destination: default_filesystem
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
            directory_namer: App\Bridge\VichUploader\MediaDirectoryNamer
            delete_on_remove: true
```

And it's not working either;
