### ISSUE TITLE
Ideas for useful features

### ISSUE THREAD

**Issue by ioleo** [dustin10/VichUploaderBundle#110]
Some ideas for new features:
- add file-serving controller for download action (modifies headers [as described here](http://stackoverflow.com/questions/11090272/how-can-i-force-a-image-download) to force download)
- add new helpers like **absolute path** or **download link** (generates path to download action)
- add file-serving controller for view action - modify file name, eg. allow accesing `web/media/010231.jpg` via link `www.mydomain.com/media/my_picture.jpg` where entity is:

``` yaml
id: 5
name: my_picture.jpg   # this could be annotated as displayNameProperty ?
path: 010231.jpg    # this is the filenameProperty
```
