### ISSUE TITLE
Path using PropertyDirectoryNamer may not be '0'?

### ISSUE THREAD

**Issue by Nexotap** [dustin10/VichUploaderBundle#1111]
Not sure if it's expected behaviour, but to me it looks like a bug. 

Here's the function I use for retrieving the directory path:
```
public function getPath()
{
    $path = strval($this->getSupplier() ? $this->getSupplier()->getId() : 0);
    return $path;
}
```

Whereas the config looks like this:
```    
mappings:
    invoice:
        uri_prefix: /documents
        upload_destination: '%kernel.project_dir%/public/documents'
        namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
        directory_namer:
            service: vich_uploader.namer_directory_property
            options: { property: 'path', transliterate: false} 
```

The idea is, returning the id of the Supplier within the entity and use it as path. In case no Supplier is defined, the path should be 0.

While every other number than 0 works, I get the following error when returning 0:

> An exception has been thrown during the rendering of a template ("Directory name could not be generated: property path is empty.").

Why should a path containing a directory named '0' not be possible?
