### ISSUE TITLE
"Directory name could not be generated: property id is empty" error

### ISSUE THREAD

**Issue by pierresimonnet** [dustin10/VichUploaderBundle#1119]
|    Q            |   A
|---------------- | ------
| Bundle version  | 1.13.2
| Symfony version | 5
| PHP version     | 7.4.0 

### Support Question
Hello,
Vich is working fine when I update a Post entity which has an image but when I create a new entity or delete the entity I get this error : "Directory name could not be generated: property id is empty."

No problem when the entity has no image that is why I guess there is something wrong with Vich.

Do you have any idea where is the problem coming from ?

Vich config :

```yaml
vich_uploader:
db_driver: orm

mappings:
    post_cover:
        uri_prefix: /images/cover
        upload_destination: '%kernel.project_dir%/public/images/cover'
        directory_namer:
            service: vich_uploader.namer_directory_property
            options: { property: 'id'}
        namer: Vich\UploaderBundle\Naming\UniqidNamer

        inject_on_load: false
        delete_on_update: true
        delete_on_remove: true
```

Thanks for your help !
