### ISSUE TITLE
Service vich_uploader.templating.helper.uploader_helper unavailable

### ISSUE THREAD

**Issue by davidromani** [dustin10/VichUploaderBundle#1126]
### BC Break Report

After 1.13.2 update, service `@vich_uploader.templating.helper.uploader_helper` is not available.

|    Q        |   A
|------------ | ------
| BC Break    | yes
| Version     | 1.13.2

#### Summary

I have an own service with this dependecies

```
    app.smart_assets_helper:
        public: true
        class: App\Service\SmartAssetsHelperService
        arguments:
            - '@vich_uploader.templating.helper.uploader_helper'
            - '@liip_imagine.cache.manager'
            - '@liip_imagine.data.manager'
            - '@liip_imagine.filter.manager'
            - '@kernel'
            - '%project_url_base%' 
```

#### Previous behavior

Everything works well.

#### Current behavior

After composer update, now I'm having this error

`The service "app.audit_pdf_builder" has a dependency on a non-existent service "vich_uploader.templating.helper.uploader_helper"
`
#### How to reproduce

I'm using Symfony 4.4 with this dependencies:

```
    "require": {
        "php": ">=7.4.0",
        "ext-calendar": "*",
        "ext-ctype": "*",
        "ext-iconv": "*",
        "ext-json": "*",
        "a2lix/translation-form-bundle": "^2.0",
        "beberlei/doctrineextensions": "^1.0",
        "doctrine/doctrine-bundle": "^2.0",
        "doctrine/orm": "^2.7",
        "egulias/email-validator": "^2.1",
        "friendsofsymfony/ckeditor-bundle": "^2.1",
        "friendsofsymfony/jsrouting-bundle": "^2.5",
        "knplabs/knp-menu-bundle": "^2.0",
        "knplabs/knp-paginator-bundle": "^3.0",
        "krixer/google-map-form-type-bundle": "^1.2",
        "lexik/maintenance-bundle": "^2.0",
        "liip/imagine-bundle": "^2.1",
        "predis/predis": "^1.1",
        "sensio/framework-extra-bundle": "^5.1",
        "snc/redis-bundle": "^3.2",
        "sonata-project/admin-bundle": "^3.52",
        "sonata-project/doctrine-orm-admin-bundle": "^3.10",
        "sonata-project/user-bundle": "^4.0",
        "stof/doctrine-extensions-bundle": "^1.3",
        "symfony/asset": "4.4.*",
        "symfony/console": "4.4.*",
        "symfony/dotenv": "4.4.*",
        "symfony/expression-language": "4.4.*",
        "symfony/flex": "^1.3.1",
        "symfony/form": "4.4.*",
        "symfony/framework-bundle": "4.4.*",
        "symfony/http-client": "4.4.*",
        "symfony/intl": "4.4.*",
        "symfony/monolog-bundle": "^3.1",
        "symfony/orm-pack": "*",
        "symfony/process": "4.4.*",
        "symfony/security-bundle": "4.4.*",
        "symfony/serializer-pack": "*",
        "symfony/swiftmailer-bundle": "^3.1",
        "symfony/translation": "4.4.*",
        "symfony/twig-bundle": "4.4.*",
        "symfony/validator": "4.4.*",
        "symfony/web-link": "4.4.*",
        "symfony/webpack-encore-bundle": "^1.2",
        "symfony/yaml": "4.4.*",
        "tattali/calendar-bundle": "^1.1",
        "twig/extensions": "^1.5",
        "vich/uploader-bundle": "^1.13",
        "whiteoctober/tcpdf-bundle": "^1.0"
    },
```
