### ISSUE TITLE
[Filesystemstorage] Diffrent web directory

### ISSUE THREAD

**Issue by ioleo** [dustin10/VichUploaderBundle#113]
Hi,

due to my hosts configuration I had to rename `web` directory. I renamed it to `pub`.

Also, changed my vich_uploader configuration to:

``` yaml
vich_uploader:
    db_driver:  orm
    gaufrette:  false
    storage:    vich_uploader.storage.file_system
    mappings:
        gallery_album:
            uri_prefix:           /media/gallery/album
            upload_destination:   %kernel.root_dir%/../pub/media/gallery/album
            namer:                vich_uploader.namer_uniqid
            inject_on_load:       true
            delete_on_remove:     true
            delete_on_update:     true
```

Yet I'm getting "stat failed for file..." error from AvalancheImagineBundle which is trying to generate a thumbnail for this image.

Full error message in `prod.log`:

> **[2013-01-31 16:36:34] request.INFO:** Matched route "_imagine_upload_widget_thumbnail" (parameters: "_controller": "imagine.controller:filter", "filter": "gallery_album_thumb", "path": "media/gallery/album/a85f03f41446f069dd36e79f20c523b22105f5d4", "_route": "_imagine_upload_widget_thumbnail") [] []
> **[2013-01-31 16:36:34] security.INFO:** Populated SecurityContext with an anonymous Token [] []
> **[2013-01-31 16:36:34] request.ERROR:** Symfony\Component\HttpKernel\Exception\NotFoundHttpException: Image doesn't exist (uncaught exception) at /vendor/avalanche123/imagine-bundle/Avalanche/Bundle/ImagineBundle/Controller/ImagineController.php line 65 [] []
> **[2013-01-31 16:36:34] security.DEBUG:** Write SecurityContext in the session [] []

[See Line 65 of AvalancheImagineBundle ImagineController.php](https://github.com/avalanche123/AvalancheImagineBundle/blob/develop/Controller/ImagineController.php#L65)

If I understand correct:
- something is wrong with my `vich_uploader` config
- imagine can't find vich_uploader file (error in logs)
- no thumbnail is generated (becouse of error)
- so on my website there are no images :(
