### ISSUE TITLE
Route or File not found (API Platform, Google Storage and Flysystem)

### ISSUE THREAD

**Issue by blacxi** [dustin10/VichUploaderBundle#1148]
|    Q            |   A
|---------------- | ------
| Bundle version  | 1.14
| Symfony version | 4.4.11
| PHP version     | 7.4.4 
| API Platform (api-platform/api-pack) | 1.1
| league/flysystem-bundle | 1.4
| superbalist/flysystem-google-storage | 7.2

### Support Question

I am using api for my project.
After having correctly configured the bundle to upload files to the Bucket GSP (Google Cloup Platform), I am currently having a problem uploading a file from the Bucket GSP.

When I try to download a file that does exist in the bucket, I have a 404 error in the resolution of the route on the Symfony side, for example i have the file in my bucket "020000013-5f280a8c5c443442641542.pdf", but i have this error .

**Error:** 
`No route found for "GET /files/billing/020000013-5f280a8c5c443442641542.pdf"`

I don't know if you can help me but in case here is my current setup.

```
vich_uploader:
    db_driver: orm
    storage: flysystem

    mappings:
        billing_file:
            uri_prefix: /files/billing
            upload_destination: '%env(resolve:VICH_UPLOADER_BILLING_FILE_DEST)%'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
    metadata:
        auto_detection: false
        directories:
            - {path: '%kernel.project_dir%/config/vich_uploader/order', namespace_prefix: 'Domain\Order'}
```

`
**.env**
VICH_UPLOADER_BILLING_FILE_DEST=billing.files.dist
`

**Fysystem**
```
services:
    Google\Cloud\Storage\StorageClient:
        public: true
        arguments:
            - { keyFile: '%env(json:file:resolve:GOOGLE_STORAGE_API_KEY)%' }

flysystem:
    storages:
        billing.files.dist:
            adapter: 'gcloud'
            options:
                client: 'Google\Cloud\Storage\StorageClient'
                bucket: '%env(resolve:GOOGLE_STORAGE_BUCKET)%'
                prefix: 'api/order/billing'
```

Thank you,
See you soon

**Comment by garak** [comment]
How do you get the path of file?

**Comment by blacxi** [comment]
Hi,

I use this `$this->storage->resolveUri($billingFile, 'file');` for generate my path of file.

If you want to know more, i have an BillingFile Entity like this :

```
use Domain\Core\Entity\File;
use Domain\Core\Identifier\IdentifierInterface;

class BillingFile extends File
{
    /** @var string|null */
    private $billingNumber;

    private IdentifierInterface $orderId;

    public function __construct(IdentifierInterface $identifier, \SplFileInfo $file, IdentifierInterface $orderIdentifier)
    {
        parent::__construct($identifier, $file);
        $this->orderId = $orderIdentifier;
    }

    public function setBillingNumber(?string $billingNumber): void
    {
        $this->billingNumber = $billingNumber;
    }

    public function getBillingNumber(): ?string
    {
        return $this->billingNumber;
    }

    public function getFileName(): string
    {
        return $this->name;
    }
}
```

And i implement a `DataTransformerInterface` of API Platform in my `BillingFileDataTransformer` like this :

```
use ApiPlatform\Core\DataTransformer\DataTransformerInterface;
use Domain\Order\DTO\BillingFile as BillingFileDTO;
use Domain\Order\Entity\BillingFile;
use Vich\UploaderBundle\Storage\StorageInterface;

final class BillingFileDataTransformer implements DataTransformerInterface
{
    /** @var StorageInterface */
    private $storage;

    public function __construct(StorageInterface $storage)
    {
        $this->storage = $storage;
    }

    /**
     * @param BillingFile $billingFile
     *
     * @return BillingFileDTO
     */
    public function transform($billingFile, string $to, array $context = [])
    {
        $dto = new BillingFileDTO();

        $dto->identifier = $billingFile->getIdentifier();
        $dto->contentUrl = $this->storage->resolveUri($billingFile, 'file');
        $dto->createdAt = $billingFile->getCreatedAt();
        $dto->updatedAt = $billingFile->getUpdatedAt();
        $dto->billingNumber = $billingFile->getBillingNumber();
        $dto->name = $billingFile->getFileName();

        return $dto;
    }
    ...
```

And this is my result on Get :
```
...
"billing": {
    "@id": "/billing_files/d99667b1-3326-4ea9-b834-6d874279de49",
    "identifier": "d99667b1-3326-4ea9-b834-6d874279de49",
    "contentUrl": "/files/billing/020000013-5f280a8c5c443442641542.pdf",
    "createdAt": "2020-09-02T10:08:21+00:00",
    "updatedAt": "2020-09-02T10:08:21+00:00",
    "billingNumber": null,
    "name": "020000013-5f280a8c5c443442641542.pdf"
}
...
```

Thank you for your answer.

**Comment by garak** [comment]
But when you get the path of your file, you can't use it without referencing your bucket, right?
That file is not inside your project.

**Comment by blacxi** [comment]
Yes, it's right, 

When i'm using the local conf i don't have the error message, like this :

**.env**
`VICH_UPLOADER_BILLING_FILE_DEST=billing.files`

**Fysystem**
```
flysystem:
    storages:
        billing.files:
            adapter: 'local'
            options:
                directory: '%kernel.project_dir%/public/files/billing'
```

So i don't know how and where, i must to add in my code :

```
If GCP get file from here
```

If you have an id, let me know please.

Thank you :-)
