### ISSUE TITLE
disabling metadata cache does not work anymore

### ISSUE THREAD

**Issue by Nemo64** [dustin10/VichUploaderBundle#1150]
### Bug Report

|    Q            |   A
|---------------- | ------
| BC Break        | no
| Bundle version  | 1.15.0
| Symfony version | 4.4.13
| PHP version     | 7.4.9

#### Summary

Disabling the metadata cache does not work anymore.

#### Current behavior

When using this configuration, I get a "Directory "" was not created" message while running `cache:clear`.
```yaml
vich_uploader:
    db_driver: orm
    storage: flysystem

    metadata:
        cache: none
```

This issue is in the `CacheWarmer` introduced by #1135. It does not handle that the cache might be disabled.
