### ISSUE TITLE
enabing metadata cache with a directoy specied does not work

### ISSUE THREAD

**Issue by Nemo64** [dustin10/VichUploaderBundle#1151]
### Bug Report

|    Q            |   A
|---------------- | ------
| BC Break        | no
| Bundle version  | 1.15.0
| Symfony version | 4.4.13
| PHP version     | 7.4.9

#### Summary

Defining a cache directory in the configuration does not work.

#### Current behavior

If you specify a cache directy, it will create it on cache warmup (i think) but if the directoy is missing, i get a `The directory "/tmp/vich_uploader" does not exist.`. It seems it does not try to create it.

#### How to reproduce

```yaml
vich_uploader:
    db_driver: orm
    storage: flysystem

    metadata:
        cache: file
        file_cache:
            dir: '/tmp/vich_uploader'
```

`rm -rf tmp/vich_uploader`

Then try to do anything

#### Expected behavior

If the directory does not exist, then it should be created.
