### ISSUE TITLE
VichImageType not showing image with directory namer and EasyAdmin3

### ISSUE THREAD

**Issue by ChangePlaces** [dustin10/VichUploaderBundle#1154]
### Bug Report

I am uploading an image with the subdir directory namer using EasyAdmin3. The image successfully uploads to the subdir, however, using a VichImageType field to show the image attempts to show the image in the root image directory (e.g. /foo.jpg), not the sub dir (images/product/f/o/foo.jpg). Without the directory namer, the image shows without issue as I can set the base path. When editing the entity, the image shows successfully with a VichImageType for the imageFile property

This is the vich uploader config:

```
        product_image:
            uri_prefix: /images/products
            upload_destination: '%kernel.project_dir%/public/images/products'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
            directory_namer:
                service: Vich\UploaderBundle\Naming\SubdirDirectoryNamer
                options: {chars_per_dir: 1, dirs: 3} # will create directory "a/b" for "abcdef.jpg"
```

and this is the Easy Admin CRUD config

```
            ImageField::new('imageFile')
                ->setFormType(VichImageType::class)
                ->onlyOnForms()
        ,

            ImageField::new('image')
                ->setFormType(VichImageType::class)
//                ->setBasePath('images/products')
                ->hideOnForm()
         ,
```

and the imageFile property on the product class

```
    /**
     * @Vich\UploadableField(mapping="product_image", fileNameProperty="image")
     * @var File|null
     */
    private $imageFile;

```

|    Q            |   A
|---------------- | ------
| BC Break        | yes/no
| Bundle version  | 1.15.0 
| Symfony version | 5.1.5
| PHP version     | 7.4
