### ISSUE TITLE
Not working with Flysystem memory adapter

### ISSUE THREAD

**Issue by pieterw2w** [dustin10/VichUploaderBundle#1163]
### Bug Report

|    Q            |   A
|---------------- | ------
| BC Break        | no
| Bundle version  | 1.15.0 
| Symfony version | 5.1.8
| PHP version     | 7.4.10

#### Summary

We use this bundle in an Api Platform project. We wanted to make integration tests of the upload functionality. In our test environment flysystem is using the memory adapter, so no actual files are created. Memory Adapter is not extending AbstractAdapter (see https://github.com/thephpleague/flysystem-memory/issues/9), so it is missing the applyPathPrefix method which results in a fatal error in VichUploaderBundle

#### Current behavior

Trying to upload a file with the memory adapter will end up with this error:
`
Error: Call to undefined method League\Flysystem\Memory\MemoryAdapter::applyPathPrefix()

/var/www/projects/lesapp-backend/vendor/vich/uploader-bundle/src/Storage/FlysystemStorage.php:70
/var/www/projects/lesapp-backend/vendor/vich/uploader-bundle/src/Storage/AbstractStorage.php:85
/var/www/projects/lesapp-backend/vendor/vich/uploader-bundle/src/Injector/FileInjector.php:28
/var/www/projects/lesapp-backend/vendor/vich/uploader-bundle/src/Handler/UploadHandler.php:63
/var/www/projects/lesapp-backend/vendor/vich/uploader-bundle/src/EventListener/Doctrine/UploadListener.php:43
/var/www/projects/lesapp-backend/vendor/symfony/doctrine-bridge/ContainerAwareEventManager.php:58
`

#### How to reproduce

In Symfony:
Set up Flysystem with the memory adapter:
versions:
vich_uploader: 1.15.0
league flysystem: 1.1.3
league flysystem-bundle: 1.5.0
league_flysystem_memory: 1.0.2

In flysystem.yaml:
```
flysystem:
    storages:
        storage.import.source:
            adapter: 'memory
```
In vichy_uploader.yaml:
```
vich_uploader:
    db_driver: orm
    storage: flysystem

    mappings:
        file_upload:
            inject_on_load: true
            uri_prefix: ''
            upload_destination: storage.upload.submissions
```

When you try to upload you are greeted with a fatal error as mentioned above here.
#### Expected behavior

Make the upload work with memory adapter.
