### ISSUE TITLE
Delete entity when file is deleting

### ISSUE THREAD

**Issue by devcut** [dustin10/VichUploaderBundle#1172]
|    Q            |   A
|---------------- | ------
| Bundle version  | 1.16.0 
| Symfony version | 5.1.8
| PHP version     | 7.4.6

### Support Question

I want to remove attachment entity when file is deleting but the flush not working.

services.yaml

```yaml
app.listener.removed_file_listener:
    class: App\EventListener\RemovedFileListener
    tags:
      - { name: kernel.event_listener, event: vich_uploader.post_remove }
```

EventListener

```php
class RemovedFileListener
{
    private EntityManagerInterface $em;

    public function __construct(EntityManagerInterface $em)
    {
        $this->em = $em;
    }

    // Make sure a file entity object is removed after the file is deleted
    public function onVichuploaderPostremove(Event $event)
    {
        // Get the file object
        $entity = $event->getObject();

        // Remove the file object from the database
        $this->em->remove($entity);
        $this->em->flush();
    }
}
```
