### ISSUE TITLE
Async AWS S3 issue in VichUploaderBundle

### ISSUE THREAD

**Issue by fd6130** [dustin10/VichUploaderBundle#1176]
|    Q            |   A
|---------------- | ------
| Bundle version  | 1.16.1 
| Symfony version | 5.2
| PHP version     | 7.4

### Support Question

I have setup Async AWS with `thephpleague/flysystem-bundle` and `async-aws/async-aws-bundle` in VichUploaderBundle, when i upload an image it return me an exception:

```
Return value of Vich\UploaderBundle\Storage\FlysystemStorage::getFilesystem() must be an instance of League\Flysystem\FilesystemInterface, instance of League\Flysystem\Filesystem returned
```

Here is my basic config in flysystem and vich:

```
flysystem:
    storages:
        upload.storage:
            # adapter: 'local'
            # options:
            #     directory: '%kernel.project_dir%/public/storage/upload'
            adapter: 'asyncaws'
            options:
                client: 'async_aws.client.s3' # The service ID of the AsyncAws\S3\S3Client instance
                bucket: 'ap-southeast-1'
                prefix: 'optional/path/prefix'

```

```
vich_uploader:
    db_driver: orm
    storage: flysystem
    # metadata:
    #    file_cache:
    #        dir: '%kernel.build_dir%/vich_uploader'
    mappings:
       file_upload:
           uri_prefix: /storage/upload
           upload_destination: upload.storage
           namer:
                service: Vich\UploaderBundle\Naming\HashNamer
                options: { algorithm: 'sha256', length: 50 }
```

**Comment by fd6130** [comment]
Ok even i switch back to local instead of aws s3 the issue still persist:

```
flysystem:
    storages:
        upload.storage:
            adapter: 'local'
            options:
                directory: '%kernel.project_dir%/public/storage/upload'
```

My guessing is because of the flysystem 2.0, anyone can confirm that?
