### ISSUE TITLE
On delete entity : Directory name could not be generated: property id is empty (ON create too)

### ISSUE THREAD

**Issue by imajim** [dustin10/VichUploaderBundle#1180]
Hello,

config : 
```
vich_uploader:
    db_driver: orm
    mappings:
        employe_photos:
            uri_prefix: '%app.path.employe_photos%'
            upload_destination: '%kernel.project_dir%/public%app.path.employe_photos%'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
            inject_on_load: false
            delete_on_update: true
            delete_on_remove: true
            directory_namer:
                service: vich_uploader.namer_directory_property
                options: { property: 'id', transliterate: true}
        negociateur_photos:
            uri_prefix: '%app.path.negociateur_photos%'
            upload_destination: '%kernel.project_dir%/public%app.path.negociateur_photos%'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
            directory_namer:
                service: vich_uploader.namer_directory_property
                options: { property: 'id', transliterate: true}
        agence_photos:
            uri_prefix: '%app.path.agence_photos%'
            upload_destination: '%kernel.project_dir%/public%app.path.agence_photos%'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
            directory_namer:
                service: vich_uploader.namer_directory_property
                options: { property: 'id', transliterate: true}
```
services.yaml :
```
parameters:
    app.path.employe_photos: /uploads/photos/employes
    app.path.negociateur_photos: /uploads/photos/negociateurs
    app.path.agence_photos: /uploads/photos/agences
```

On delete "Employe" ID 1 who had a photo (public/uploads/photos/employes/1/grand-bleu-beach-resort-02-602544c251071061558894.jpg), i 've got this error : 

<img width="1054" alt="image" src="https://user-images.githubusercontent.com/13310096/107736084-7f1e0200-6d01-11eb-86fb-1fac6a42820a.png">

No error on update or when i update employe with delete checked 
thanks to help me ^^

UPDATE 1 : 
the entity ID is null : 
```
vendor/vich/uploader-bundle/src/Naming/PropertyDirectoryNamer.php:74:
object(App\Entity\Employe)[684]
  private 'id' => null
...
```
