### ISSUE TITLE
Incorrect documentation for integrating oneup/flysystem-bundle

### ISSUE THREAD

**Issue by fd6130** [dustin10/VichUploaderBundle#1198]
### Bug Report

|    Q            |   A
|---------------- | ------
| BC Break        | ~yes~ no
| Bundle version  | 1.17.0 
| Symfony version | 5.2.6
| PHP version     | 7.4.16

#### Summary
Current documentation for integrate oneup/flysystem-bundle will lead to error exception when uploading an image.

#### Current behavior

When i upload image it give me an error as below:

```php
Service "default_filesystem" not found: the container inside "Symfony\Component\DependencyInjection\Argument\ServiceLocator" is a smaller service locator that only knows about the "oneup_flysystem.default_filesystem_filesystem" service.
```

#### How to reproduce
This is my `vich_uploader.yaml` :

```yaml
vich_uploader:
    db_driver: orm
    storage: flysystem

    mappings:
       file_upload:
           uri_prefix: /var/storage/local
           upload_destination: default_filesystem # I think because of this one
           namer:
                service: Vich\UploaderBundle\Naming\HashNamer
                options: { algorithm: 'sha512', length: 128 }
           directory_namer:
                service: Vich\UploaderBundle\Naming\CurrentDateTimeDirectoryNamer
                options:
                    date_time_format: 'Y/m/d' # will create directory "2018/23/09" for current date "2018-09-23"
                    date_time_property: uploadedAt # see above example
           inject_on_load: true
```

And this is `oneup_flysystem.yaml`:

```yaml
# Read the documentation: https://github.com/1up-lab/OneupFlysystemBundle/tree/master/Resources/doc/index.md
oneup_flysystem:
    adapters:
        default_adapter:
            local:
                location: '%kernel.project_dir%/var/storage/local'
    filesystems:
        default_filesystem:
            adapter: default_adapter
            mount: default_filesystem
```

#### Expected behavior

Successfully upload image.

**Comment by fd6130** [comment]
### Update

If i add `oneup_flysystem.default_filesystem_filesystem` it would work. 

```yaml
vich_uploader:
    db_driver: orm
    storage: flysystem

    mappings:
       file_upload:
           uri_prefix: /var/storage/local
           upload_destination: oneup_flysystem.default_filesystem_filesystem
           namer:
                service: Vich\UploaderBundle\Naming\HashNamer
                options: { algorithm: 'sha512', length: 128 }
           directory_namer:
                service: Vich\UploaderBundle\Naming\CurrentDateTimeDirectoryNamer
                options:
                    date_time_format: 'Y/m/d' # will create directory "2018/23/09" for current date "2018-09-23"
                    date_time_property: uploadedAt # see above example
           inject_on_load: true
```

But the image path were incorrect when i `dd()` the image file, it give me `path: "2021/04/20"` instead of `path: "..../var/storage/local/2021/04/20/...."`.
