### ISSUE TITLE
Flushing the Entity Manager will cause update in datetime field

### ISSUE THREAD

**Issue by fd6130** [dustin10/VichUploaderBundle#1205]
### Bug Report

|    Q            |   A
|---------------- | ------
| BC Break        | no
| Bundle version  | 1.16.1 
| Symfony version | 5.2.9
| PHP version     | 7.4.18

#### Summary

Fetching a vich entity from database and flush it will cause update in datetime field.

#### Current behavior

If i query a vich entity from database, the flush will cause update in datetime field of that entity.

```php
$entity = $fileUploaderRepository->findOneBy(['id' => 1]);

$entityManager->flush(); // just do nothing and flush it
```

#### How to reproduce

vich_uploader.yaml

```yaml
vich_uploader:
    db_driver: orm
    storage: flysystem

    mappings:
       file_upload:
           uri_prefix: /var/storage/local
           upload_destination: default_filesystem
           namer:
                service: Vich\UploaderBundle\Naming\HashNamer
                options: { algorithm: 'sha512', length: 128 }
           directory_namer:
                service: Vich\UploaderBundle\Naming\CurrentDateTimeDirectoryNamer
                options:
                    date_time_format: 'Y/m/d' # will create directory "2018/23/09" for current date "2018-09-23"
                    date_time_property: uploadedAt # see above example
           inject_on_load: true
```

FileUploader.php (vich entity)

```php
use App\Repository\FileUploaderRepository;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\HttpFoundation\File\File;
use Vich\UploaderBundle\Mapping\Annotation as Vich;
use Symfony\Bridge\Doctrine\IdGenerator\UuidV4Generator;
use Symfony\Component\Uid\Uuid;

/**
 * @ORM\Entity(repositoryClass=FileUploaderRepository::class)
 * @Vich\Uploadable
 */
class FileUploader
{
    /**
     * @ORM\Id
     * @ORM\Column(type="uuid", unique=true)
     * @ORM\GeneratedValue(strategy="CUSTOM")
     * @ORM\CustomIdGenerator(class=UuidV4Generator::class)
     */
    private $id;

    /**
     * @Vich\UploadableField(mapping="file_upload", fileNameProperty="fileName", size="size", mimeType="mimeType", originalName="originalName")
     */
    private $file;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $fileName;

    /**
     * @ORM\Column(type="datetime_immutable", nullable=true)
     */
    private $uploadedAt;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $mimeType;

    /**
     * @ORM\Column(type="bigint", nullable=true)
     */
    private $size;

    /**
     * @ORM\Column(type="text", nullable=true)
     */
    private $originalName;

    /**
     * @ORM\Column(type="boolean")
     */
    private $isApplied = false;

    public function getId(): ?Uuid
    {
        return $this->id;
    }

    public function setFile(?File $file = null): self
    {
        $this->file = $file;

        if (null !== $file) {
            // It is required that at least one field changes if you are using doctrine
            // otherwise the event listeners won't be called and the file is lost
            $this->uploadedAt = new \DateTimeImmutable();
        }
        
        return $this;
    }

    public function getFile(): ?File
    {
        return $this->file;
    }


    public function getFileName(): ?string
    {
        return $this->fileName;
    }

    public function setFileName(?string $fileName): self
    {
        $this->fileName = $fileName;

        return $this;
    }

    public function getUploadedAt(): ?\DateTimeImmutable
    {
        return $this->uploadedAt;
    }

    public function setUploadedAt(\DateTimeImmutable $uploadedAt): self
    {
        $this->uploadedAt = $uploadedAt;

        return $this;
    }

    public function getIsApplied(): ?bool
    {
        return $this->isApplied;
    }

    public function setIsApplied(bool $isApplied): self
    {
        $this->isApplied = $isApplied;

        return $this;
    }

    public function getMimeType(): ?string
    {
        return $this->mimeType;
    }

    public function setMimeType(?string $mimeType): self
    {
        $this->mimeType = $mimeType;

        return $this;
    }

    public function getSize(): ?string
    {
        return $this->size;
    }

    public function setSize(?string $size): self
    {
        $this->size = $size;

        return $this;
    }

    public function getOriginalName(): ?string
    {
        return $this->originalName;
    }

    public function setOriginalName(?string $originalName): self
    {
        $this->originalName = $originalName;

        return $this;
    }
```

#### Expected behavior

The datetime field should not being updated by flush if nothing change in the entity itself.
