### ISSUE TITLE
League\\Flysystem\\Filesystem instance instead of League\\Flysystem\\FilesystemInterface issue

### ISSUE THREAD

**Issue by alexglvr** [dustin10/VichUploaderBundle#1207]
Symfony : 5.2.8
APi-platform : 2.6.3
vich/uploader : 1.16.1
league/flysystem: 2.0.8
league/flysystem-aws-s3-v3 : 2.0.6
league/flysystem-bundle  : 2.0.0

Hello,

I try making vich/uploader and flysystem work on my api-platform server, but get the following issue : 

`Vich\\UploaderBundle\\Storage\\FlysystemStorage::getFilesystem() must be an instance of League\\Flysystem\\FilesystemInterface, instance of League\\Flysystem\\Filesystem returned`

my vich_uploader.yaml is

```
vich_uploader:
    db_driver: orm
    storage: flysystem

    mappings:
        media_object:
            uri_prefix: /media
            upload_destination: default.storage
            # Will rename uploaded files using a uniqueid as a prefix.
            namer: Vich\UploaderBundle\Naming\OrignameNamer
        tdata_object:
            uri_prefix: /tracksdata
            upload_destination: awss3.storage
            # Will rename uploaded files using a uniqueid as a prefix.
            namer: Vich\UploaderBundle\Naming\OrignameNamer
```
and flysystem.yaml
```
flysystem:
    storages:
        default.storage:
            adapter: 'local'
            options:
                directory: '%kernel.project_dir%/var/storage/default'
        awss3.storage:
            adapter: 'aws'
            # visibility: public # Make the uploaded file publicly accessible in S3
            options:
                client: 'Aws\S3\S3Client' # The service ID of the Aws\S3\S3Client instance
                bucket: '%env(AWS_S3_BUCKET_NAME)%'
                prefix: 'data'
```
What did I miss ?
Thank you for your help
Alex
