### ISSUE TITLE
VichUploader does not display images in the symfonyCloud

### ISSUE THREAD

**Issue by atassamweb** [dustin10/VichUploaderBundle#1221]
|    Q            |   A
|---------------- | ------
| Bundle version  | 1.18.0 
| Symfony version | 5.3
| PHP version     | 7.4

### Support Question

I am facing a problem with the display of the uploaded images in the symfonycloud.
I checked with the ssh, the image is sent to the images /cars folder but I cannot display it.

#.symfony.cloud.yaml
```
#.symfony.cloud.yaml
name: app

type: php:7.4

runtime:
    extensions:
        - apcu
        - mbstring
        - sodium
        - ctype
        - gd
        - iconv
        - pdo_mysql
        

#variables:
#    php:
#        # uncomment on PHP 7.4+
#        #opcache.preload: /app/config/preload.php

build:
    flavor: none

disk: 512

relationships:
    database: "mydatabase:mysql"

web:
    locations:
        "/":
            root: "public"
            expires: 1h
            passthru: "/index.php"
        '/public':
            root: 'public/images/voitures'
            scripts: false
            allow: true


mounts:
    "/var": { source: local, source_path: var }
    '/public/images/voitures': { source: local, source_path: public/images/voitures }

hooks:
    build: |
        set -x -e

        curl -fs https://get.symfony.com/cloud/configurator | (>&2 bash)
        
        (>&2 symfony-build)

    deploy: |
        set -x -e

        (>&2 symfony-deploy)

```
```
#.viche_uploader.yaml

vich_uploader:
  db_driver: orm

  mappings:
    voiture_image:
      uri_prefix: /images/voitures
      upload_destination: '%kernel.project_dir%/web/images/voitures'
      namer: Vich\UploaderBundle\Naming\SmartUniqueNamer

    user_image:
      uri_prefix: /images/users
      upload_destination: '%kernel.project_dir%/web/images/users'
      namer: Vich\UploaderBundle\Naming\SmartUniqueNamer

```
```
 {% if voiture.imageName1 %}
         <div class="carousel-item">
              <img src="{{ vich_uploader_asset(voiture, 'imageFile1') | imagine_filter('thumb') }}" 		class="d-block w-100 card-img-top" alt="{{ voiture.imageName1 }}">
         </div>
 {% endif %}
```
What I want is to be able to display the uploaded images in my views.
But when I inspect my image I get this error:
Source image for path "images/voitures/01-61263223806e7284603437.jpg" could not be found.

I look forward to your help and have a good day.
