### ISSUE TITLE
Unrecognized option "type" under "vich_uploader.metadata" in PHP8

### ISSUE THREAD

**Issue by pottink** [dustin10/VichUploaderBundle#1233]
### Bug Report

|    Q            |   A
|---------------- | ------
| BC Break        | yes/no
| Bundle version  | 1.18
| Symfony version | 5.3
| PHP version     | 8.0

#### Summary

When using following configuration:

```
vich_uploader:
    db_driver: orm

    metadata:
        type: attribute

    mappings:
        attachments:
            uri_prefix: /attachments
            upload_destination: '%kernel.project_dir%/public/attachments'

```

I get following error:

```
Unrecognized option "type" under "vich_uploader.metadata". Available options are "auto_detection", "cache", "directories", "file_cache".
```

This is suggested by the docs.
