### ISSUE TITLE
delete_on_update not working

### ISSUE THREAD

**Issue by julien-lmnr** [dustin10/VichUploaderBundle#1252]
### Bug Report

|    Q            |   A
|---------------- | ------
| BC Break        | no
| Bundle version  | dev-master
| Symfony version | 6.0.1
| PHP version     | 8.0.14

Hello everyone,

It seems that the **delete_on_update** parameter is not working correctly, at least not in my case with the **dev-master version**.
Strange because the **delete_on_remove** parameter works very well.

```php
#[Vich\Uploadable]
class PageImageBlock
{
    #[Vich\UploadableField(mapping: 'page_image', fileNameProperty: 'imageName')]
    private ?File $imageFile = null;

    #[ORM\Column(type: 'string', length: 255)]
    private ?string $imageName = null;

    public function getImageFile(): ?File
    {
        return $this->imageFile;
    }

    public function setImageFile(?File $imageFile): self
    {
        $this->imageFile = $imageFile;

        if (null !== $imageFile) {
            $this->updatedAt = new DateTime();
        }

        return $this;
    }

    public function getImageName(): ?string
    {
        return $this->imageName;
    }

    public function setImageName(?string $imageName): self
    {
        $this->imageName = $imageName;

        return $this;
    }
}
```

```yaml
vich_uploader:
    db_driver: orm

    metadata:
        type: attribute

    mappings:
        page_image:
            uri_prefix: '%app.path.page_image%'
            upload_destination: '%kernel.project_dir%/public%app.path.page_image%'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
```

Do you have an idea ?
