### ISSUE TITLE
PHP 8 and Vich\Uploadable

### ISSUE THREAD

**Issue by Julen10** [dustin10/VichUploaderBundle#1264]
|    Q            |   A
|---------------- | ------
| Bundle version  | 1.19.0
| Symfony version | 6.0.2
| PHP version     | 8.0.14

### Support Question

I´m getting "The class "App\Entity\Foo" is not uploadable." error.

Having this:

```
#[ORM\Entity(repositoryClass: FooRepository::class)]
#[Vich\Uploadable]
class Foo
{
}
```
The configuration is correct because if I put the following, its works:
```
#[ORM\Entity(repositoryClass: FooRepository::class)]
/**
* @Vich\Uploadable
*/
class Foo
{
}
```

Any tips on this problem? Thanks

**Comment by Julen10** [comment]
Solved here:
```
# config/packages/vich_uploader.yaml or app/config/config.yml
vich_uploader:
    db_driver: orm        # or mongodb or phpcr - default db driver
    twig: true            # set to false to disable twig integration
    form: true            # set to false to disable form integration
    storage: file_system  # or gaufrette or flysystem
    metadata:
        auto_detection: true
        cache: file
        type: annotation    # or attribute
    mappings:
        product_image:
            uri_prefix: /uploads    # uri prefix to resource
            upload_destination: ~   # gaufrette storage fs id, required
            namer: ~                # specify a file namer service for this entity, null default
            directory_namer: ~      # specify a directory namer service for this entity, null default
            delete_on_remove: true  # determine whether to delete file upon removal of entity
            delete_on_update: true  # determine wheter to delete the file upon update of entity
            inject_on_load: false   # determine whether to inject a File instance upon load
            db_driver: phpcr        # override the default db driver set above. Allow separate driver per mapping
        # ... more mappings
```
vich_uploader.metadata.type: attribute

**Comment by mi6th** [comment]
@Julen10 I have an extra question: Do you use also Doctrine mappings with `attribute`?

I have two projects (SF 5.4 and SF 6.0.2) one is ported to PHP 8 with PHP attributes and another is a fresh one also with PHP 8 attributes. The VichUploaderBundle mapping is OK but Doctrine doesn't *see* the entity `UploadableField` property: in the ported project it drops fields in the database that were previously used as VichUploaderBundle mappings with an `UploadableField` *annotation* and in the new project Doctrine doesn't detect the VichUploaderBundle mapping for properties with `UploadableField` attribute.

**Comment by Julen10** [comment]
@mi6th Yes, im using only `attribute` for both of them.

**Comment by kermitsxb** [comment]
Gosh ! This made me struggle a lot... Thought it was using attribute by default

**Comment by xero88** [comment]
i'm using `attribute` but i get the error 

```
# api/config/packages/vich_uploader.yaml
vich_uploader:
  db_driver: orm
  metadata:
    type: attribute
  mappings:
    media_object:
      uri_prefix: /media
      upload_destination: '%kernel.project_dir%/public/media'
      namer: Vich\UploaderBundle\Naming\OrignameNamer
```
