### ISSUE TITLE
Service "default_filesystem" not found: the container inside

### ISSUE THREAD

**Issue by habibun** [dustin10/VichUploaderBundle#1276]
### Bug Report

**package version:**
```
"oneup/flysystem-bundle": "^4.4",
"vich/uploader-bundle": "^1.19"
```

  Symfony   Version:  5.4.6                                          

  PHP Version:   7.4.28                                               

my config:
```
vich_uploader:
    db_driver: orm
    twig: true
    storage: flysystem

    mappings:
        product_image:
            uri_prefix: uploads/images/products
            upload_destination: default_filesystem
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer

```
```
oneup_flysystem:
    adapters:
        default_adapter:
            local:
                location: '%kernel.project_dir%/public/uploads/images/products'
    filesystems:
        default_filesystem:
            adapter: default_adapter
            alias: League\Flysystem\Filesystem

```

#### Summary

getting erro: 

#### Current behavior
When i try to upload, i am getting this erro:
Service "default_filesystem" not found: the container inside "Symfony\Component\DependencyInjection\Argument\ServiceLocator" is a smaller service locator that is empty...

#### How to reproduce

**method 1:**
install and configure "vich/uploader-bundle": "^1.19" 
install  and configure "oneup/flysystem-bundle": "^4.4",
make basic crud and try to add new image

or 

**method 2:**
git clone https://github.com/habibun/vich-uploader-bundle
checkout branch: 1.x
install composer and symfony serve
browser root url -> product -> new -> fill the form and submit

#### Expected behavior

Should able to upload image

**Update**: also tried this `oneup_flysystem.default_filesystem_filesystem`, same error
