### ISSUE TITLE
Unable to write file at location

### ISSUE THREAD

**Issue by habibun** [dustin10/VichUploaderBundle#1281]
Hello,
I am using VichUploaderBundle with flysystem to manage uploads to s3. 
I would expect a permission issue but tried possible option.
I can't really figure out what I do wrong...

My mappings are defined as follow:

```
oneup_flysystem:
    adapters:
        default_adapter:
            local:
                location: '%kernel.project_dir%/public/uploads/images/products'
        aws_adapter:
            awss3v3:
                client: aws.s3_client
                bucket: 'vich'
                prefix: '/product'
                options:
                    ACL: bucket-owner-full-control
    filesystems:
        default_filesystem:
            adapter: default_adapter
            mount: default_filesystem
        aws_filesystem:
            adapter: aws_adapter
            mount: aws_filesystem
            visibility: public
            directory_visibility: public
```

```
vich_uploader:
    db_driver: orm
    twig: true
    storage: flysystem

    mappings:
        product_image:
            uri_prefix: uploads/images/products
#            upload_destination: oneup_flysystem.default_filesystem_filesystem
            upload_destination: oneup_flysystem.aws_filesystem_filesystem
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer

```
Entity           
```
    /**
     * @Vich\UploadableField(mapping="product_image", fileNameProperty="image.name", size="image.size", mimeType="image.mimeType", originalName="image.originalName", dimensions="image.dimensions")
     *
     * @var File|null
     */
    private $imageFile;
```
    
                
what am I missing?

Thanks!

reproduce:
git clone https://github.com/habibun/vich-uploader-bundle 
composer install
symfony serve 
goto: http://127.0.0.1:8000/product/new

try to upload any picture
