### ISSUE TITLE
How to get ImageFile - informations after Upload in Service

### ISSUE THREAD

**Issue by agonyz** [dustin10/VichUploaderBundle#1304]
|    Q            |   A
|---------------- | ------
| Bundle version  | 1.20.0 
| Symfony version | 6.1.2
| PHP version     | 8.1

### Support Question

I followed the instructions and implemented my entity like in this example: https://github.com/dustin10/VichUploaderBundle/blob/master/docs/usage.md#step-2-link-the-upload-mapping-to-an-entity

My config looks like this:
```yml
vich_uploader:
    db_driver: orm
    metadata:
        type: attribute

    mappings:
        message_image:
            #uri_prefix: /images/files/messages/uploads
            upload_destination: '%kernel.project_dir%/files/messages/uploads'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer

            delete_on_remove: true
            delete_on_update: false
            inject_on_load: false
```

I don't use Symfony Form Component but rather upload the image via a frontend javascript framework.
The upload works and i get data in my database about the files.
Also when I remove a file via entityManager the database record and the according file are getting removed.

My database looks like this:
| id | updated_at | image_name | image_size |
| -- | ------------- | --------- | ------ |
| 1 | 2022-07-20 14:09:43 | test.png | 29607 |
| 2 | ,, | ,, | ,, |

I want to attach my uploaded image via service to an email object.
Therefore i need the complete path to my image.

In my Service I tried to get the image path like this:
```php
$file->getImageFile()->getRealPath()
```

But it showed that my ImageFile is null.

How can I get my ImageFile + all the needed variables like the path? 
Do I even use the ImageFile - Field from my Entity to get the path?
Or how would one get the Path and other informations about the image in a service?
