### ISSUE TITLE
Image does not delete from folder

### ISSUE THREAD

**Issue by plumedours** [dustin10/VichUploaderBundle#1341]
Hi,
(Please excuse me for my English, I'm French and I use Google Trad)

I've been looking for and testing solutions that I find on this github or other sites for a few days, but my problem is still there.

I use EasyAdmin for the management of an image gallery, and I installed VichUploader. Everything goes well to add an image, I see it appear in the folder that I have defined as well as in my database.
Editing is also going well, if I change the image, it changes the image in the folder as well as in the database.

On the other hand, where it does not go, it is for the deletion. From EasyAdmin, if I click "Delete", the database updates fine and deletes the corresponding row, but the image still remains in the folder. Couldn't find a solution to remove it from the folder.

Here are my files:

vich_uploader.yaml:

```yaml
vich_uploader:
    db_driver: orm

    metadata:
        type: attribute

    mappings:
       gallery:
            uri_prefix: 'images/gallery'
            upload_destination: '%kernel.project_dir%public/images/gallery%'
            inject_on_load: true
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
            delete_on_remove: true
            delete_on_update: true
```

service.yaml:

```yaml
# This file is the entry point to configure your own services.
# Files in the packages/ subdirectory configure your dependencies.

# Put parameters here that don't need to change on each machine where the app is deployed
# https://symfony.com/doc/current/best_practices.html#use-parameters-for-application-configuration
parameters:
  gallery: /assets/images/gallery

services:
  # default configuration for services in *this* file
  _defaults:
    autowire: true # Automatically injects dependencies in your services.
    autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.

  # makes classes in src/ available to be used as services
  # this creates a service per class whose id is the fully-qualified class name
  App\:
    resource: "../src/"
    exclude:
      - "../src/DependencyInjection/"
      - "../src/Entity/"
      - "../src/Kernel.php"

  # add more service definitions when explicit configuration is needed
  # please note that last definitions always *replace* previous ones
```

My GalleryEntity (Some lines are in comments, because I tested several ways to do it, in vain) :
```php
<?php

namespace App\Entity;

use DateTimeInterface;
use Doctrine\ORM\Mapping as ORM;
use App\Repository\GalleryRepository;
use Symfony\Component\HttpFoundation\File\File;
use Vich\UploaderBundle\Mapping\Annotation as Vich;
use Vich\UploaderBundle\Entity\File as EmbeddedFile;

#[ORM\Entity(repositoryClass: GalleryRepository::class)]
#[Vich\Uploadable]

class Gallery
{

    public function __construct()
    {
        $this->image = new EmbeddedFile();
    }

    #[ORM\Id]
    #[ORM\Column]
    #[ORM\GeneratedValue]
    private ?int $id = null;

    // #[ORM\Embedded(class: "Vich\UploaderBundle\Entity\File")]
    // private ?EmbeddedFile $image = null;

    // TEST
    #[Vich\UploadableField(mapping: 'gallery', fileNameProperty: 'imageName')]
    private ?File $imageFile = null;

    #[ORM\Column(type: 'string')]
    private ?string $imageName = null;
    // FIN TEST

    #[ORM\Column(length: 255)]
    private ?string $title = null;

    #[ORM\Column(type: 'datetime')]
    private ?\DateTimeInterface $updatedAt = null;


    /**
     * If manually uploading a file (i.e. not using Symfony Form) ensure an instance
     * of 'UploadedFile' is injected into this setter to trigger the update. If this
     * bundle's configuration parameter 'inject_on_load' is set to 'true' this setter
     * must be able to accept an instance of 'File' as the bundle will inject one here
     * during Doctrine hydration.
     *
     * @param File|\Symfony\Component\HttpFoundation\File\UploadedFile|null $imageFile
     */
    public function setImageFile(?File $imageFile = null): void
    {
        $this->imageFile = $imageFile;

        if (null !== $imageFile) {
            // It is required that at least one field changes if you are using doctrine
            // otherwise the event listeners won't be called and the file is lost
            $this->updatedAt = new \DateTimeImmutable();
        }
    }

    
    public function getImageFile(): ?File
    {
        return $this->imageFile;
    }
    
    public function getId(): ?int
    {
        return $this->id;
    }
    
    // public function setImage(EmbeddedFile $image): void
    // {
    //     $this->image = $image;
    // }

    // public function getImage(): ?EmbeddedFile
    // {
    //     return $this->image;
    // }

    //TEST
    public function setImageName(?string $imageName): void
    {
        $this->imageName = $imageName;
    }

    public function getImageName(): ?string
    {
        return $this->imageName;
    }
    //FIN TEST

    public function getTitle(): ?string
    {
        return $this->title;
    }

    public function setTitle(string $title): self
    {
        $this->title = $title;

        return $this;
    }

    public function getUpdatedAt(): ?DateTimeInterface
    {
        return $this->updatedAt;
    }

    public function setUpdatedAt(?DateTimeInterface $updatedAt): self
    {
        $this->updatedAt = $updatedAt;

        return $this;
    }
}
```

My GalleryCrudController :
```php
<?php

namespace App\Controller\Admin;

use App\Entity\Gallery;
use EasyCorp\Bundle\EasyAdminBundle\Field\Field;
use EasyCorp\Bundle\EasyAdminBundle\Field\ImageField;
use EasyCorp\Bundle\EasyAdminBundle\Controller\AbstractCrudController;
use Vich\UploaderBundle\Form\Type\VichImageType;

class GalleryCrudController extends AbstractCrudController
{
    public static function getEntityFqcn(): string
    {
        return Gallery::class;
    }

    public function configureFields(string $pageName): iterable
    {

        return [
            yield Field::new('title'),
            yield Field::new('updatedAt'),
            yield ImageField::new('imageName')
                ->setUploadDir('assets/images/gallery')
                ->setBasePath('assets/images/gallery'),
        ];
    }
}
```

My GalleryType :
```php
<?php

namespace App\Form;

use App\Entity\Gallery;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;
use Symfony\Component\Form\Extension\Core\Type\TextType;
use Vich\UploaderBundle\Form\Type\VichImageType;

class GalleryType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options): void
    {
        $builder
            ->add('photoFile', VichImageType::class, [
                'allow_delete' => true,
            ]);
    }

    public function configureOptions(OptionsResolver $resolver): void
    {
        $resolver->setDefaults([
            'data_class' => Gallery::class,
        ]);
    }
}
```

Please help me because I don't know what to do anymore. I tried to create an EventListener, but I didn't succeed, probably I misconfigured.

In addition to this deletion problem, the Namer does not work either, in the vich_uploader.yaml I have configured to have a unique name, but the name of the image that is uploaded remains its original name.

Thank you for your help !

**Comment by plumedours** [comment]
Alright, I made some progress in my problem. Here are the files :

vich_uploader.yaml :

```yaml
vich_uploader:
    db_driver: orm

    metadata:
        type: attribute

    mappings:
       gallery:
            uri_prefix: 'images/gallery'
            upload_destination: '%kernel.project_dir%/assets/images/gallery'
            inject_on_load: true
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
            delete_on_remove: true
            delete_on_update: true
```

services.yaml :

```yaml
parameters:
  gallery: /assets/images/gallery
```

My entity Gallery.php :

```php
<?php

namespace App\Entity;

use DateTimeInterface;
use Doctrine\ORM\Mapping as ORM;
use App\Repository\GalleryRepository;
use Symfony\Component\HttpFoundation\File\File;
use Vich\UploaderBundle\Mapping\Annotation as Vich;

#[ORM\Entity(repositoryClass: GalleryRepository::class)]
#[Vich\Uploadable]

class Gallery
{
    #[ORM\Id]
    #[ORM\Column(type: 'integer')]
    #[ORM\GeneratedValue(strategy: 'AUTO')]
    private ?int $id = null;

    #[Vich\UploadableField(mapping: 'gallery', fileNameProperty: 'imageName')]
    private ?File $imageFile = null;

    #[ORM\Column(type: 'string')]
    private ?string $imageName = null;

    #[ORM\Column(length: 255)]
    private ?string $title = null;

    #[ORM\Column(type: 'datetime')]
    private ?\DateTimeInterface $updatedAt = null;

    /**
     * If manually uploading a file (i.e. not using Symfony Form) ensure an instance
     * of 'UploadedFile' is injected into this setter to trigger the update. If this
     * bundle's configuration parameter 'inject_on_load' is set to 'true' this setter
     * must be able to accept an instance of 'File' as the bundle will inject one here
     * during Doctrine hydration.
     *
     * @param File|\Symfony\Component\HttpFoundation\File\UploadedFile|null $imageFile
     */
    public function setImageFile(?File $imageFile = null): void
    {
        $this->imageFile = $imageFile;

        if (null !== $imageFile) {
            // It is required that at least one field changes if you are using doctrine
            // otherwise the event listeners won't be called and the file is lost
            $this->updatedAt = new \DateTimeImmutable();
        }
    }
    
    public function getImageFile(): ?File
    {
        return $this->imageFile;
    }
    
    public function getId(): ?int
    {
        return $this->id;
    }

    public function setImageName(?string $imageName): void
    {
        $this->imageName = $imageName;
    }

    public function getImageName(): ?string
    {
        return $this->imageName;
    }

    public function getTitle(): ?string
    {
        return $this->title;
    }

    public function setTitle(string $title): self
    {
        $this->title = $title;

        return $this;
    }

    public function getUpdatedAt(): ?DateTimeInterface
    {
        return $this->updatedAt;
    }

    public function setUpdatedAt(?DateTimeInterface $updatedAt): self
    {
        $this->updatedAt = $updatedAt;

        return $this;
    }
}
```

And my GalleryCrudController.php :

```php
<?php

namespace App\Controller\Admin;

use App\Entity\Gallery;
use EasyCorp\Bundle\EasyAdminBundle\Field\Field;
use Vich\UploaderBundle\Form\Type\VichImageType;
use EasyCorp\Bundle\EasyAdminBundle\Controller\AbstractCrudController;

class GalleryCrudController extends AbstractCrudController
{
    public static function getEntityFqcn(): string
    {
        return Gallery::class;
    }

    public function configureFields(string $pageName): iterable
    {

        return [
            Field::new('title'),
            Field::new('updatedAt'),
            Field::new('imageFile')
                ->setFormType(VichImageType::class)
                ->setTranslationParameters(['form.label.delete'=>'Supprimer']),
        ];
    }
}
```

The problem I have now is that in EasyAdmin I get the full path to the image, as you can see in this screenshot :
[Screenshot](https://ibb.co/JydtVkV)

I would like to have the name of the image, and not its path, because when I go to "Edit", this is what I have:
[Screenshot](https://ibb.co/tBM16cf)
