### ISSUE TITLE
After upgrading to 2.1.1 I got an error when calling to vich_uploader_asset

### ISSUE THREAD

**Issue by macaso** [dustin10/VichUploaderBundle#1376]
### BC Break Report

|    Q        |   A
|------------ | ------
| BC Break    | yes
| Version     | 2.1.1

#### Summary

I've upgraded VichUploaderBundle from 2.0.1 to 2.1.1. After this upgrade, when I try to show an image with `vich_uploader_asset` I got this error: "Attempted to call an undefined method named "asset" of class "Vich\UploaderBundle\Twig\Extension\UploaderExtension"."

#### Previous behavior

Using `vich_uploader_asset` the url of an image is written in a Twig template

#### Current behavior

It crashes with an error: "Attempted to call an undefined method named "asset" of class "Vich\UploaderBundle\Twig\Extension\UploaderExtension"."

#### How to reproduce

My configuration is really simple:

vich_uploader.yaml
```
vich_uploader:
    db_driver: orm

    mappings:
      logo_event:
        uri_prefix: /images
        upload_destination: '%kernel.project_dir%/public/images'
        namer: Vich\UploaderBundle\Naming\UniqidNamer
        directory_namer:
          service: Vich\UploaderBundle\Naming\SubdirDirectoryNamer
          options: { chars_per_dir: 1, dirs: 2}
```

base/index.html:
```
{% if prova.logotipProva %}
    <img src="{{ vich_uploader_asset(prova, 'imatgeLogotip') }}" alt="{{ prova.nom }}" class="img-responsive"/>
{% endif %}
```

All is working correctly with VichUploaderBundle 2.0.1. If I upgrade to 2.1.1, reloading the index page I got this error:

`Attempted to call an undefined method named "asset" of class "Vich\UploaderBundle\Twig\Extension\UploaderExtension".`

Offending code:
```
        return $this->render('base/index.html.twig', [
            'properesProves' => $properesProves,
        ]);
```
