### ISSUE TITLE
Vich\Uploadable not working correctly with OneToOne relation

### ISSUE THREAD

**Issue by davidrojo** [dustin10/VichUploaderBundle#1409]
### Bug Report

|    Q            |   A
|---------------- | ------
| BC Break        | no
| Bundle version  | 2.2.0
| Symfony version | 5.4.21
| PHP version     | 8.2.5

#### Summary

When having an entity with a relation `OneToOne` with other entity with a `VichUploadable` file, on changing the relation and flushing the related entity is not properly updated in php, although in database is properly updated. A refresh of the entity is required to get the updated value.

#### Current behavior

I have an entity Item with a relation OneToOne with ItemImage that is a Vich\Uploadable entity. When updating this entity, after flushing it to the database, the previous entity is loaded in the relation without an Id instead the new entity that has been stored in the database.

```
$item = $this->entityManager->getRepository(Item::class)->findOneById(1);
// (1) $item->getImage() returns a Doctrine proxy ItemImage with an Id
$item->setImage(new ItemImage($file));
// (2) $item->getImage() returns an ItemImage without an id, as it has not been saved into the database
$this->entityManager->flush();
// (3) $item->getImage() returns the ItemImage object (not the proxy) of step (1) with id=null, instead of the new ItemImage with the id
```

#### How to reproduce

This is the source code:

Item.php

```
#[ORM\Entity]
class Item
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column(type: 'integer')]
    protected ?int $id = null;

    #[ORM\OneToOne(inversedBy: 'target', targetEntity: ItemImage::class, cascade: ['all'], orphanRemoval: true)]
    protected ?ItemImage $image = null;

    ....getters and setters
}

```

ItemImage.php

```
#[ORM\Entity]
#[Vich\Uploadable]
class ItemImage
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column(type: 'integer')]
    protected ?int $id;

    #[ORM\OneToOne(mappedBy: 'image', targetEntity: Item::class)]
    protected ?Item $target = null;

    #[Vich\UploadableField(
        mapping: 'profile',
        fileNameProperty: 'name'
    )]
    protected ?File $file = null;

    #[ORM\Column(type: 'string', length: 255)]
    #[Groups(['GeneralRead'])]
    protected ?string $name = '';

    #[ORM\Column(type: 'datetime_immutable', nullable: true)]
    protected ?DateTimeImmutable $uploadedAt;

    public function __construct(?File $file)
    {
        $this->setFile($file);
    }

    public function setFile(?File $file): self
    {
        $this->file = $file;
        if ($file instanceof UploadedFile) {
            $this->uploadedAt = new DateTimeImmutable();
        }
        return $this;
    }

    ... getters and setters
}

```

vich_uploader.yaml
```
vich_uploader:
    db_driver: orm
    metadata:
        type: attribute
    mappings:
        profile:
            uri_prefix: '%download.path.profile%'
            upload_destination: '%upload.path.profile%'
            namer: Vich\UploaderBundle\Naming\UniqidNamer
            inject_on_load: true
            directory_namer:
                service: Vich\UploaderBundle\Naming\CurrentDateTimeDirectoryNamer
                options:
                    date_time_property: uploadedAt
```

Execute the following code:

```
$file = new UploadedFile(
    $path,
    'sample-image.jpg',
    mime_content_type($path),
    false,
    true
);

$item = $this->entityManager->getRepository(Item::class)->findOneById(1);
dump($item->getImage());
```
![imagen](https://github.com/dustin10/VichUploaderBundle/assets/1050749/2f27c536-1f26-4c94-b306-9bdab10e952a)

```
$item->setImage(new ItemImage($file));
dump($item->getImage());
```
![imagen](https://github.com/dustin10/VichUploaderBundle/assets/1050749/d46debbc-d262-4699-8f0a-4b8ce03a98fb)

```
$this->entityManager->flush();
dump($item->getImage());
```
![imagen](https://github.com/dustin10/VichUploaderBundle/assets/1050749/afdefeb2-f972-41e5-9c02-1785f6c38c5b)

```
$this->entityManager->refresh($item);
dump($item->getImage());
```
![imagen](https://github.com/dustin10/VichUploaderBundle/assets/1050749/0c82bc5f-f437-423d-b190-06944c87827b)

#### Expected behavior

The third dump, shold be the same as the fourth dump. Shoud be a `ItemImage` entity with id=11 and filename ...584.jpg, instead the id is null and the filename is ...440.jpg (the original filename before being replaced).

If before setting the new image, you fully load the entity (doing a `$item->getImage()->getFile()` for example) then the first dump is not a Proxy, and it works fine. So there must be an issue with the use of Proxies.

Removing `#[Vich\Uploadable]` from `ItemImage`, works fine (although the image will not be handled) so it seems that is not an issue of doctrine.
