### ISSUE TITLE
Namer is required in configuration from 2.2 to 2.3

### ISSUE THREAD

**Issue by jannes-io** [dustin10/VichUploaderBundle#1423]
### BC Break Report

|    Q        |   A
|------------ | ------
| BC Break    | yes
| Version     | 2.3.0

#### Summary

https://github.com/dustin10/VichUploaderBundle/pull/1404/files

#### Previous behavior

`vich_uploader.mappings.namer` used to be `addDefaultsIfNotSet`, and thus not required.

#### Current behavior

`vich_uploader.mappings.namer` is now `isRequired`, and thus prevents extension to be loaded if `namer` isn't set.

#### How to reproduce

Install bundle version 2.2, set up config like:
```yaml
vich_uploader:
  db_driver: orm
  storage: flysystem
  metadata:
    type: attribute
  mappings:
    uploads:
      upload_destination: some.storage
      uri_prefix: '%env(CDN_URL)%/uploads'
```

Now update to version 2.3, container building results in:
```
Uncaught Symfony\Component\Config\Definition\Exception\InvalidConfigurationException: The child config "namer" under "vich_uploader.mappings.uploads" must be configured. in /project/vendor/symfony/config/Definition/ArrayNode.php:226
```

Minor tags should not introduce BC breaks.
