### ISSUE TITLE
Document how to get s3 URL

### ISSUE THREAD

**Issue by tacman** [dustin10/VichUploaderBundle#1434]
|    Q            |   A
|---------------- | ------
| Bundle version  | latest
| Symfony version | 6.4 || ^7
| PHP version     | 8.3

I've configured the this bundle with the Flysystem s3 adapter, and it's working as expected when uploading.

The documentation for generating URLs says that it's relative to the local public directory, but if the adapter is s3 there is no local directory.

https://github.com/dustin10/VichUploaderBundle/blob/master/docs/generating_urls.md

Ultimately I'll want go to through liip/imagine-bundle, but for now I thought I'd start with the s3 url.

Is there documentation or a demo program for uploading to s3 and then displaying the images (and thumbnails)?  I assume this is a pretty common setup.  

Possibly related to #221 and #1424 

Thanks for this bundle!

**Comment by tacman** [comment]
For now, I've put the bucket path in the config, but this will only work for public images

```yaml
    mappings:
        submissions:
            upload_destination: default.storage # Use the name you defined for your storage here
            uri_prefix: https://%env(AWS_S3_BUCKET_NAME)%.s3.us-east-2.amazonaws.com
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
```
