### ISSUE TITLE
Issue with VichUploader: unsupported MIME type "image/jpeg"

### ISSUE THREAD

**Issue by Mirieri** [dustin10/VichUploaderBundle#1435]
I am currently facing an issue with the VichUploader bundle in my Symfony project, specifically when attempting to upload an image using the multipart/form-data content type.

Here are the details of the error I encountered:

```
{
    "@context": "/api/contexts/Error",
    "@type": "hydra:Error",
    "hydra:title": "An error occurred",
    "hydra:description": "The content-type \"image/jpeg\" is not supported. Supported MIME types are \"application/ld+json\", \"application/json\", \"text/html\".",
    "trace": [
        // Error trace details
    ]
}
```

It seems that the content type "image/jpeg" is not recognized or supported, and the application is expecting one of the following MIME types: "application/ld+json", "application/json", "text/html".

I have verified my VichUploader configuration, and it appears to be correctly set up. Here is a snippet of my configuration:

```
vich_uploader:
    db_driver: orm
    mappings:
        imageFile:
            uri_prefix: /images/mob_image
            upload_destination: '%kernel.project_dir%/public/images/mob_image'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
```

My Entity model is 

```
<?php

namespace App\Entity;

use ApiPlatform\Metadata\ApiResource;
use App\Repository\MobImagesRepository;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\HttpFoundation\File\UploadedFile;
use Vich\UploaderBundle\Mapping\Annotation as Vich;
use ApiPlatform\Core\Annotation\ApiProperty;

/**
 * @ORM\Table(name="mob_images")
 * @ORM\Entity(repositoryClass=MobImagesRepository::class)
 * @Vich\Uploadable
 */
#[ApiResource]
class MobImages
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(name="source_id", type="integer")
     */
    private $sourceId;

    /**
     * @var UploadedFile|null
     * @Vich\UploadableField(mapping="imageFile", fileNameProperty="imageName")
     */
    private $imageFile;

    /**
     * @var string|null
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $imageName;

    /**
     * @var \DateTimeImmutable|null
     * @ORM\Column(type="datetime_immutable", nullable=true)
     */
    private $createdAt;

    /**
     * @ORM\Column(name="description", type="string", length=255)
     */
    private $description;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getSourceId(): ?int
    {
        return $this->sourceId;
    }

    public function setSourceId(int $sourceId): self
    {
        $this->sourceId = $sourceId;

        return $this;
    }

    public function getImageName(): ?string
    {
        return $this->imageName;
    }

    public function setImageName(?string $imageName): self
    {
        $this->imageName = $imageName;

        return $this;
    }

    public function setImageFile(?UploadedFile $imageFile = null): void
    {
        $this->imageFile = $imageFile;

        if ($imageFile) {
            $this->createdAt = new \DateTimeImmutable();
        }
    }

    public function getImageFile(): ?UploadedFile
    {
        return $this->imageFile;
    }

    public function getCreatedAt(): ?\DateTimeImmutable
    {
        return $this->createdAt;
    }

    public function setDescription(?string $description): self
    {
        $this->description = $description;

        return $this;
    }

    public function getDescription(): ?string
    {
        return $this->description;
    }

}
```
under config
/config/api_platform/
```
App\Entity\MobImages:
  collectionOperations:
    get:
      method: get
      path: /images
      filters: [ 'mobimages.search_filter', 'property_filter' ]
      normalization_context:
        groups: [ 'mobimages:collection:get' ]
      openapi_context:
        description:
          ''
        parameters:
          - name: page
            in: query
            description: 'The collection page number'
            required: false
            deprecated: false
            allowEmptyValue: false
            schema:
              type: integer
              default: 1
            style: form
            explode: false
            allowReserved: false
          - name: pagination
            in: query
            description: 'Enable or disable pagination'
            required: false
            deprecated: false
            allowEmptyValue: false
            schema:
              type: boolean
            style: form
            explode: false
            allowReserved: false
    post:
      method: post
      path: /images
      denormalization_context:
        groups: [ 'mobimages:collection:post' ]
      openapi_context:
        description:
          '<h3>Creates a Mob Images resource</h3>'
  itemOperations:
    get:
      method: get
      path: /images/{id}
      normalization_context:
        groups: [ 'mobimages:item:get' ]
    put:
      method: put
      path: /images/{id}
      denormalization_context:
        groups: [ 'mobimages:item:put' ]
      openapi_context:
        description:
          '<h3>Replaces the mobile images resource specified by the `id` parameter</h3><p>The following properties are **required** and need to be provided in the request body:
           </p>`country`<p>`farmerIsHhHead`</p>`isActive`<p>`isDeleted`</p>`name`<p>All other properties are **optional**.</p>'
    patch:
      method: patch
      path: /images/{id}
      denormalization_context:
        groups: [ 'mobimages:item:patch' ]
      openapi_context:
        description:
          '<h3>Updates the mobile images resource specified by the `id` parameter</h3><p>The following properties are **required** and need to be provided in the request body:
          </p>`farmerIsHhHead`<p>All other properties are **optional**.</p>'
```
