### ISSUE TITLE
How to use metadata with VichUploader

### ISSUE THREAD

**Issue by Mgt03** [dustin10/VichUploaderBundle#1440]
I need help to use Vich uploader on my project. 

My problem concerns the metadata of an image imported from a php form.

I have a form where users can insert images, which are saved after submitting the form. But if they insert an image with a rotation value, after saving, the image loses this value.

I have this configuration in the vich_uploader.yml file:
``` YAML
vich_uploader:
    db_driver: orm

    mappings:
        marque_image:
            uri_prefix: /marques
            upload_destination: '%kernel.project_dir%/public/marques'
            namer: Vich\UploaderBundle\Naming\UniqidNamer

            inject_on_load: true
            delete_on_update: true
            delete_on_remove: true
        document_file:
            uri_prefix: /documents
            upload_destination: '%kernel.project_dir%/documents'
            namer: Vich\UploaderBundle\Naming\UniqidNamer

            inject_on_load: true
            delete_on_update: true
            delete_on_remove: true
        dossier_file:
            uri_prefix: /dossiers/uploads
            upload_destination: '%kernel.project_dir%/dossiers/uploads'
            namer: Vich\UploaderBundle\Naming\UniqidNamer

            inject_on_load: true
            delete_on_update: true
            delete_on_remove: true
        messenger_file:
            uri_prefix: /messenger/uploads
            upload_destination: '%kernel.project_dir%/public/messenger/uploads'
            namer: Vich\UploaderBundle\Naming\UniqidNamer

            inject_on_load: true
            delete_on_update: true
            delete_on_remove: true
        photos:
            uri_prefix: /dossiers/uploads
            upload_destination: '%kernel.project_dir%/public/dossiers/uploads'
            namer: Vich\UploaderBundle\Naming\UniqidNamer

            inject_on_load: true
            delete_on_update: true
            delete_on_remove: true
```

[https://github.com/dustin10/VichUploaderBundle/blob/master/docs/usage.md](url)
This documentation show the possibility to add a 'metadata' property but I can't find how to use it after.

My entity is declared as follows :
```php
/**
 * @OA\Schema(schema="Photos")
 *
 * @Serializer\ExclusionPolicy("ALL")
 */
#[Vich\Uploadable]
#[ORM\Entity(repositoryClass: PhotoRepository::class)]
#[ORM\Table(name: 'PHOTOS')]
class Photo
{
    /**
     * @OA\Property(
     *     type="integer",
     *     description="Identifiant de la photo",
     *     example=1
     * )
     * @Serializer\Expose
     * @Serializer\Groups({"api_advertisement_index"})
     */
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column(name: 'ID', type: 'integer')]
    private $id;
    /**
     * Ce champs n'est pas exposé içi mais dans App\Serializer\LinkSerializationSubscriber.
     *
     * @OA\Property(
     *     property="path_file",
     *     type="string",
     *     description="Lien de la photo",
     *     example="http://dafokaz.docker:8090/dossiers/uploads/image.png"
     * )
     * @Serializer\SerializedName(value="path_file")
     */
    #[ORM\Column(name: 'FILE', type: 'string', length: 255, nullable: true)]
    private $pathFile;
    /**
     * @var File
     */
    #[Vich\UploadableField(mapping: 'photos', fileNameProperty: 'pathFile')]
    private $file;
    ( . . . )
```
Concerning the metadata information of the picture before and after, I have this :
Picture original :
```bash 
 array(9) {
  ["FileName"]=>
  string(12) "original.jpg"
  ["FileDateTime"]=>
  int(1711527777)
  ["FileSize"]=>
  int(13668)
  ["FileType"]=>
  int(2)
  ["MimeType"]=>
  string(10) "image/jpeg"
  ["SectionsFound"]=>
  string(24) "ANY_TAG, IFD0, THUMBNAIL"
  ["COMPUTED"]=>
  array(7) {
    ["html"]=>
    string(24) "width="244" height="207""
    ["Height"]=>
    int(207)
    ["Width"]=>
    int(244)
    ["IsColor"]=>
    int(1)
    ["ByteOrderMotorola"]=>
    int(1)
    ["Thumbnail.FileType"]=>
    int(2)
    ["Thumbnail.MimeType"]=>
    string(10) "image/jpeg"
  }
  ["Orientation"]=>
  int(3)
  ["THUMBNAIL"]=>
  array(6) {
    ["Compression"]=>
    int(6)
    ["XResolution"]=>
    string(4) "96/1"
    ["YResolution"]=>
    string(4) "96/1"
    ["ResolutionUnit"]=>
    int(2)
    ["JPEGInterchangeFormat"]=>
    int(120)
    ["JPEGInterchangeFormatLength"]=>
    int(4914)
  }
} ```
Picture saved in my app folder:
```bash
array(7) {
  ["FileName"]=>
  string(26) "6603d7c701f62441951521.jpg"
  ["FileDateTime"]=>
  int(1711527879)
  ["FileSize"]=>
  int(7072)
  ["FileType"]=>
  int(2)
  ["MimeType"]=>
  string(10) "image/jpeg"
  ["SectionsFound"]=>
  string(0) ""
  ["COMPUTED"]=>
  array(4) {
    ["html"]=>
    string(24) "width="244" height="207""
    ["Height"]=>
    int(207)
    ["Width"]=>
    int(244)
    ["IsColor"]=>
    int(1)
  }
} ```

I need to have the orientation value in the saved file ...

Does anyone have any ideas?
