### ISSUE TITLE
Image not deleted with cascade deletion.

### ISSUE THREAD

**Issue by soullivaneuh** [dustin10/VichUploaderBundle#160]
I have two entities, `Project` and `ProjectIllustration` that contains my images.

`ProjectIllustration` have a CASCADE DELETE rule on the `Project` relation ship.

If I delete a project, the images associated to the illustrations are not deleted.

`ProjectIllustration` class:

``` php
class ProjectIllustration
{
    /**
     * @var integer
     *
     * @ORM\Column(name="id", type="integer")
     * @ORM\Id
     * @ORM\GeneratedValue(strategy="AUTO")
     */
    private $id;

    /**
     * @ORM\ManyToOne(targetEntity="Project", inversedBy="illustrations")
     * @ORM\JoinColumn(name="project_id", referencedColumnName="id", onDelete="CASCADE")
     */
    private $project;

    /**
     * @var File $image
     *
     * @Assert\Image(
     *     maxSize = "2048k",
     *     minWidth = 150,
     *     minHeight = 150
     * )
     *
     * @Vich\UploadableField(mapping="project_image", fileNameProperty="imagePath")
     */
    private $image;

    /**
     * @var string $imagePath
     *
     * @ORM\Column(name="image_path", type="string", length=255)
     */
    private $imagePath;

    /* [...] */
}
```

My config file:

``` yaml
# VichUploader Configuration
vich_uploader:
    db_driver: orm
    mappings:
        customer_image:
            uri_prefix: /images/customers
            upload_destination: %kernel.root_dir%/../web/images/customers
            delete_on_remove: true
            delete_on_update: true
        team_member_image:
            uri_prefix: /images/team
            upload_destination: %kernel.root_dir%/../web/images/team
            delete_on_remove: true
            delete_on_update: true
        project_image:
            uri_prefix: /images/projects
            upload_destination: %kernel.root_dir%/../web/images/projects
            delete_on_remove: true
            delete_on_update: true
```

Wrong configuration or issue ? 

Thanks.
