### ISSUE TITLE
Unable to get filename property value error on specific image upload

### ISSUE THREAD

**Issue by soullivaneuh** [dustin10/VichUploaderBundle#162]
I have the following error when uploading a specific image:

`Unable to get filename property value: "image"`

My entity:

``` php
/**
 * @ORM\Entity
 * @Vich\Uploadable
 */
class Customer
{
    /**
     * @ORM\Id
     * @ORM\Column(type="integer")
     * @ORM\GeneratedValue(strategy="AUTO")
     */
    private $id;

    /**
     * @var string $name
     *
     * @ORM\Column(name="name", type="string", length=100)
     */
    private $name;

    /**
     * @var string $website
     *
     * @ORM\Column(name="website", type="string", length=255)
     */
    private $website;

    /**
     * @var File $image
     *
     * @Assert\Image(
     *     maxSize = "2048k",
     *     minWidth = 150,
     *     minHeight = 150
     * )
     *
     * @Vich\UploadableField(mapping="customer_image", fileNameProperty="imagePath")
     */
    private $image;

    /**
     * @var string $imagePath
     *
     * @ORM\Column(name="image_path", type="string", length=255)
     */
    private $imagePath;
```

My config:

``` yaml
vich_uploader:
    db_driver: orm
    mappings:
        customer_image:
            uri_prefix: /images/customers
            upload_destination: %kernel.root_dir%/../web/images/customers
            namer: vich_uploader.namer_uniqid
            delete_on_remove: true
            delete_on_update: true
```

And the accused image ! :)

![ataos](https://f.cloud.github.com/assets/1698357/1390405/227d9206-3bed-11e3-82b6-781de42d7a1c.png)

For the moment, I got this error only with this image, not the other, weird isn't it ?

Any idea ?
