### ISSUE TITLE
protected 'file' => null

### ISSUE THREAD

**Issue by vittore** [dustin10/VichUploaderBundle#209]
Hi,

all go right but after a composer update I get this error:
every $entity->getFile() get a null.

This some details:

```
vich_uploader:
    db_driver: orm
    gaufrette: false
    mappings:
        map_file:
            uri_prefix: /mappe
            upload_destination: %kernel.root_dir%/../files/mappe
            directory_namer: directory_namer_using_azienda
            namer: file_namer.with_extension          
            delete_on_update: true   
```

and

```
/**
 * @ORM\Entity
 * @ORM\HasLifecycleCallbacks
 * @Vich\Uploadable
 */
class Mappa
{
    /**
     * @ORM\Id
     * @ORM\Column(type="integer")
     * @ORM\GeneratedValue(strategy="AUTO")
     */
    private $id;

    /**
     * @Assert\File(
     *     maxSize="40M"
     * )
     * @Vich\UploadableField(mapping="map_file", fileNameProperty="fileName")
     *
     * @var File $file
     */
    protected $file;

    /**
     * @ORM\Column(type="string", length=255, name="file_name")
     *
     * @var string $fileName
     */
    protected $fileName;
```

If I upload a new file all go right (no error, correct folder position, file saved,...).

Any ideas?
v.
