### ISSUE TITLE
Multiples files edit

### ISSUE THREAD

**Issue by Sorow** [dustin10/VichUploaderBundle#222]
Hi,

I've searching on StackOverFlow and issues who exist but I don't find the solution for my problem.

I've an Annonce and Photos entities, it's a One(annonce)ToMany(photos) with a bidirectional relation. 

For the create an annonce I've no problem, the bundle works fine I can upload multiples files in once. 

**The problem is I can't remove any photo with update form**.

I think the problem come form view, I'm don't really know.

Update.html.twig, who propose modify all the annonce and photos in same time:

``` twig
{{ form_label(form.photos, ' ') }}
{{ form_widget(form.photos) }}
```

This view make appears many input type file as photo I upload when a create my annonce. 

So I try to do this: 

``` php
{% for photo in annonce.photos %}

                            <a href="#" class="suppr-btn" title="Delete this file"><i class="icon-trash"></i></a>
                            {% set url = vich_uploader_asset(photo, 'image') %}
                            <a href="{{ asset(url) }}" data-lightbox="image">
                                <img src="{{ asset(url) }}" alt="Miniature photo" class="rounded w100">
                            </a>
                            <input type="hidden" value="{{ url }}" name="immo_annoncebundle_annonce[photos][{{ photo.id }}][image]" id="immo_annoncebundle_annonce_photos_{{ photo.id }}_image">

                    {% endfor %}
```

The click on remove button, remove this input from DOM.

Here is my controller:

``` php
public function updateAnnonceAction($id)
    {
        $em = $this->getDoctrine()->getManager();

        $annonce = $em->getRepository('ImmoAnnonceBundle:Annonce')
                      ->findCompleteAnnonceById($id);
        $form = $this->createForm(new AnnonceType, $annonce);

        $request = $this->get('request');
        if ($request->getMethod() == 'POST') {
            $form->bind($request);

            if ($form->isValid()) {

                $em = $this->getDoctrine()->getManager();
                $em->persist($annonce);
                $em->flush();
            }
        }

        return $this->render('ImmoAnnonceBundle:Admin/Annonce:update.html.twig', array('annonce' => $annonce,
         'form' => $form->createView()
                                                                                      )
                            );
    }
```

Here is my config.yml:

``` yml
knp_gaufrette:
    stream_wrapper: ~
    adapters:
        uploads_adapter:
            local:
                directory: %kernel.root_dir%/../web/img/uploads

    filesystems:
        uploads_image_fs:
            adapter:    uploads_adapter

vich_uploader:
    db_driver: orm
    twig: true
    gaufrette: true
    storage:   vich_uploader.storage.gaufrette
    mappings:
        uploads_image:
            delete_on_remove: true
            delete_on_update: true
            inject_on_load: true
            uri_prefix:         img/uploads
            upload_destination: uploads_image_fs
            namer: vich_uploader.namer_uniqid
```

Entity Annonce: 

``` php
class Annonce
{ 
// ...
/**
  * @ORM\OneToMany(targetEntity="Immo\AnnonceBundle\Entity\Photo", mappedBy="annonce", cascade={"persist", "remove"})
   */
    private $photos;
```

Entity Photo: 

``` php
class Photo
{
// ...
/**
     * @Assert\File(
     *     maxSize="1M",
     *     mimeTypes={"image/png", "image/jpeg", "image/pjpeg"}
     * )
     * @Vich\UploadableField(mapping="uploads_image", fileNameProperty="url")
     *
     * @var File $image
     */
    protected $image;

    /**
     * @ORM\Column(type="string", length=255, name="url")
     *
     * @var string $url
     */
    protected $url;

    /**
     * @var string
     *
     * @ORM\Column(name="alt", type="string", length=255, nullable=true)
     */
    private $alt;

    /**
     * @ORM\ManyToOne(targetEntity="Immo\AnnonceBundle\Entity\Annonce", inversedBy="photos")
     */
    private $annonce;

    /**
     * @ORM\Column(type="datetime", nullable=true)
     *
     * @var \DateTime $updatedAt
     */
    protected $updatedAt;
// ...
public function setImage($image)
    {
        $this->image = $image;

        if ($this->image instanceof UploadedFile) {
            $this->updatedAt = new \DateTime('now');
        }

        return $this;
    }
```

And my form type:

``` php
// AnnonceType :
$builder->add('photos', 'collection', array('type' => new PhotoType(),
                                                'allow_add' => true,
                                                'allow_delete' => true,
                                                'by_reference' => false,
                                                )
                  )
// PhotoType: 
$builder->add('image', 'file')
```

I don't found the part of doc who speak about that, maybe I miss something about rendering of form or in controller...

Thanks!
