### ISSUE TITLE
Sftp upload dont work on las commit

### ISSUE THREAD

**Issue by plozmun** [dustin10/VichUploaderBundle#247]
With the last update does not work the upload that i have configured by sftp. 

My config file is:

```
vich_uploader:
    db_driver: mongodb
    gaufrette: true
    storage: vich_uploader.storage.gaufrette
    mappings:
        gallery_image:
            uri_prefix: %cdn_path%/images/gallery
            delete_on_remove: true
            upload_destination: gallery_image_fs    
            namer: vich_uploader.namer_uniqid
            delete_on_remove: true
            inject_on_load: true  
```

And the gaufrete config:

```
knp_gaufrette:
    stream_wrapper: 
        filesystems:
            gallery: gallery_image_fs
    adapters:
        gallery_adapter:
            sftp:
                sftp_id: vivados_cdn.sftp
                directory: /html/images/gallery
                create: true
    filesystems:       
        gallery_image_fs:
            adapter:    gallery_adapter  
```
