### ISSUE TITLE
variables in upload dir

### ISSUE THREAD

**Issue by inmarelibero** [dustin10/VichUploaderBundle#25]
Hi, let's say I want to keep separate upload folders for users (by id), and I have this config.yml:

```
vich_uploader:
    db_driver: orm
    mappings:
        user_profile_image:
            upload_dir: %kernel.root_dir%/../web/uploads/user_profiles
```

My aim is to have many folders inside `user_profiles`, named for example by id:

```
[...]/user_profiles/1/
[...]/user_profiles/2/
[...]/user_profiles/4/
[...]/user_profiles/5/
[...]/user_profiles/10/
...
```

created automatically passing some parameter somewhere. is it achievable?
