### ISSUE TITLE
File injection does not seems to work

### ISSUE THREAD

**Issue by ioleo** [dustin10/VichUploaderBundle#303]
My config:

``` yaml
vich_uploader:
    db_driver:  orm
    gaufrette:  false
    storage:    vich_uploader.storage.file_system
    mappings:
        mapping_name:
            uri_prefix:           /path
            upload_destination:   %kernel.root_dir%/../private/path
            namer:                vich_uploader.namer_origname
            inject_on_load:       true
            delete_on_remove:     true
            delete_on_update:     true
```

So.. the file is succesfully stored. The Path property is set to filename. The file exists in my `/private/path` directory and is valid.

However, when I do `$item = $repository->find($id);` and `var_dump($item->getFile())` it says `null`. What is wrong?
