### ISSUE TITLE
Can't use VichFileType when having multiple file upload fields on a single Entity

### ISSUE THREAD

**Issue by Restless-ET** [dustin10/VichUploaderBundle#310]
So here's the thing... I've an entity with multiple File properties.
When using the default form type for file I can upload all files without any problem, but when I change my form to use the `'vich_file'` things no longer work properly and I'm only able to upload a file on the last File field of the form.
Not only does it upload just the file from the last field but after saving, when rendering the form again, it seems that the file is loaded into all file upload fields. :\

The default File form type gives me no visual indication that a file has already been uploaded so the VichFileType seems like a good alternative for it, but I cannot get it to work properly. :(

Am I missing something?
Any ideas/thoughts regarding this? Any suggestions will be very much appreciated.

**EDIT:** Just an idea (crazy one maybe but)... do we need to declare a mapping for each file (field/property) that I want to upload? As I recall, while using version 0.9.0 I didn't need to do such configuration. Has this changed?

I've already tried some different approaches, this is where I stand right now:
- Snippet of my entity

``` php
use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\Validator\Constraints as Assert;
use Symfony\Component\HttpFoundation\File\File;
use Symfony\Component\HttpFoundation\File\UploadedFile;
use Vich\UploaderBundle\Mapping\Annotation as Vich;

/**
 * @ORM\Table("real_estate")
 * @ORM\Entity
 * @Vich\Uploadable
 */
class RealEstate
{
    // ...
    /** @var File $characterizationSheetFile
     * @Assert\File(maxSize="3M")
     * @Vich\UploadableField(mapping="realestate_documents", fileNameProperty="characterizationSheet") */
    private $characterizationSheetFile;

    /** @var string
     * @ORM\Column(name="characterization_sheet", type="string", length=255, nullable=true) */
    private $characterizationSheet;

    /** @var File $energyCertificateFile
     * @Assert\File(maxSize="3M")
     * @Vich\UploadableField(mapping="realestate_documents", fileNameProperty="energyCertificate") */
    private $energyCertificateFile;

    /** @var string
     * @ORM\Column(name="energy_certificate", type="string", length=255, nullable=true) */
    private $energyCertificate;

   // ...
   /** Set characterizationSheetFile
     *
     * @param File|null $characterizationSheetFile The characterizationSheetFile file
     *
     * @return Service
     */
    public function setCharacterizationSheetFile($characterizationSheetFile)
    {
        if ($characterizationSheetFile) {
            $this->characterizationSheetFile = $characterizationSheetFile;

            if ($characterizationSheetFile instanceof UploadedFile) {
                $this->updatedAt = new \DateTime();
            }
        }
        return $this;
    }
    /** Get characterizationSheetFile
     *
     * @return File
     */
    public function getCharacterizationSheetFile()
    {
        return $this->characterizationSheetFile;
    }

    /** Set energyCertificateFile
     *
     * @param File|null $energyCertificateFile The energyCertificateFile file
     *
     * @return Service
     */
    public function setEnergyCertificateFile($energyCertificateFile)
    {
        if ($energyCertificateFile) {
            $this->energyCertificateFile = $energyCertificateFile;

            if ($energyCertificateFile instanceof UploadedFile) {
                $this->updatedAt = new \DateTime();
            }
        }
        return $this;
    }
    /** Get energyCertificateFile
     *
     * @return File
     */
    public function getEnergyCertificateFile()
    {
        return $this->energyCertificateFile;
    }
}
```
- My configurations regarding VichUploader and VichFileType usage

``` yaml
vich_uploader:
    db_driver: orm
    twig: true
    gaufrette: false
    storage: vich_uploader.storage.file_system
    mappings:
        realestate_documents:
            uri_prefix: '/uploads/realestate'
            upload_destination: '%kernel.root_dir%/../web/uploads/realestate'
            namer: ~
            directory_namer: ~
            delete_on_remove: true
            delete_on_update: true
            inject_on_load: true

twig:
    # ...
    form:
        resources:
            - 'VichUploaderBundle:Form:fields.html.twig'
```
- Snippet of my form

``` php
public function buildForm(FormBuilderInterface $builder, array $options)
 {
        $builder
            // ....
            ->add('characterizationSheetFile', 'vich_file', array(
                'mapping' => 'realestate_documents',
                'allow_delete' => false,
                'required' => false,
                'label' => 'label.characterizationSheet'))
            ->add('energyCertificateFile', 'vich_file', array(
                'mapping' => 'realestate_documents',
                'allow_delete' => false,
                'required' => false,
                'label' => 'label.energyCertificate'));
}
```
- Snippet of my twig template

``` html+php

<div class="my_tests_form">
  {{ form_start(form) }}
    <div id="sf_fieldset_files" class="tabcontent">
        <table>
            <tbody>
                {{ form_row( form.characterizationSheetFile ) }}
                {{ form_row( form.energyCertificateFile ) }}
            </tbody>
        </table>
    </div>
  {{ form_end(form) }}
</div>

```
