### ISSUE TITLE
Problem with configuration

### ISSUE THREAD

**Issue by ama3ing** [dustin10/VichUploaderBundle#334]
Hi guys, I've tried to setup this bundle through guide, but I can't get it working...

So my entity looks like:

``` php
<?php

**
 * @Vich\Uploadable
 * @ORM\Entity
 * @UniqueEntity("email", groups={"registration"})
 * @ORM\Table(name="my_user")
 */
class User extends BaseUser
{

//...

    /**
     * @var File
     *
     * @Vich\UploadableField(mapping="profile_picture", fileNameProperty="profilePictureS3Key")
     * @Assert\Image(
     *     maxSize = "2048k",
     *     mimeTypes = {"image/jpeg", "image/png", "image/gif"},
     *     mimeTypesMessage = "Please upload a valid image. Supported types are `image/jpeg`, `image/png`, `image/gif`",
     *     minWidth = 100,
     *     minHeight = 100,
     *     groups={"profile_picture"}
     * )
     */
    protected $image;

//....

    public function setImage(File $image)
    {
        $this->image = $image;

        if ($image) {
            // It is required that at least one field changes if you are using doctrine
            // otherwise the event listeners won't be called and the file is lost
            $this->updatedAt = new \DateTime('now');
        }

        return $this;
    }
```

My controller look like

``` php
<?php
    public function uploadProfilePictureAction(Request $request)
    {
        $user = $this->getUser();

        $form = $this->createForm(new ProfilePictureType(), $user);
        $form->handleRequest($request);

        if($form->isValid()) {
            $manager = $this->getDoctrine()->getManager();

            $manager->persist($user);
            $manager->flush();

            return null;
        }

        return $form;
    }
```

My bundle config

``` yml
vich_uploader:
    db_driver: orm
    gaufrette: true
    storage:   vich_uploader.storage.gaufrette

    mappings:
        profile_picture:
            uri_prefix:         /images/profile
            upload_destination: s3_filesystem
            delete_on_update:   true
            delete_on_remove:   true

```

Form code:

``` php
<?php
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder
            ->add('image', 'file')
        ;

    }
```

The problem is that file is not uploaded while no exceptions are thrown.
What am I doing wrong?

Thanks in advance.
