### ISSUE TITLE
Help configuring it

### ISSUE THREAD

**Issue by waltercruz** [dustin10/VichUploaderBundle#346]
My entity:

```
Dialog\BaseBundle\Entity\Convocation:
    type: entity
    table: convocation
    id:
        id:
            type: integer
            nullable: false
            unsigned: false
            comment: ''
            id: true
            generator:
                strategy: SEQUENCE
    fields:
        name:
            type: string
            nullable: false
            length: 255
            fixed: false
            comment: ''
        start:
            type: date
            nullable: true
            comment: ''
        end:
            type: date
            nullable: true
            comment: ''
        startReference:
            type: date
            nullable: true
            comment: ''
            column: start_reference
        endReference:
            type: date
            nullable: true
            comment: ''
            column: end_reference
        startExecution:
            type: date
            nullable: true
            comment: ''
            column: start_execution
        endExecution:
            type: date
            nullable: true
            comment: ''
            column: end_execution
        pathFormalization:
            type: string
            nullable: true
            length: 100
            fixed: false
            comment: ''
            column: path_formalization
    lifecycleCallbacks: {  }
```

My vich yml setting:

```
Dialog\BaseBundle\Entity\Convocation:
    image:
        mapping:           path_formalization
        filename_property: file_name
```

and my config.

```
vich_uploader:
    db_driver: orm # or mongodb or propel or phpcr

    mappings:
        image_mapping:
            uri_prefix:         /images
            upload_destination: %kernel.root_dir%/../web/images/convocation
            inject_on_load:     true
            delete_on_update:   true
            delete_on_remove:   true
```

when running, I'm getting this error:

ContextErrorException: Notice: Undefined index: path_formalization in /Users/waltercruz/devel/dialogos-setoriais/vendor/vich/uploader-bundle/DependencyInjection/Compiler/RegisterPropelModelsPass.php line 34
