### ISSUE TITLE
AWSS3 with Flysystem timeout

### ISSUE THREAD

**Issue by jernejpangersic** [dustin10/VichUploaderBundle#351]
Hi,

I'm trying to use this bundle with the AWSS3 (using Flysistem). When I try to upload files, I get this error: 

```
Error retrieving credentials from the instance profile metadata server. When you are not running inside of Amazon EC2, you must provide your AWS access key ID and secret access key in the "key" and "secret" options when creating a client or provide an instantiated Aws\Common\Credentials\CredentialsInterface object. ([curl] 28: Connection timed out after 5000 milliseconds [url] http://169.254.169.254/latest/meta-data/iam/security-credentials/)
```

```
// config.yml
oneup_flysystem:
    adapters:
        jp.flysystem_adapter:
            awss3:
                client: jp.s3_client
                bucket: jpuploads
                prefix: ~
    filesystems:
        image_fs:
            adapter:    jp.flysystem_adapter
            mount:      image_fs
```

```
// config.yml
vich_uploader:
    db_driver: orm

    flysystem: true
    storage: vich_uploader.storage.flysystem

    mappings:
        profile_picture:
            #uri_prefix: web
            upload_destination: image_fs
            namer:              vich_uploader.namer_uniqid
            delete_on_remove:   true
        advertisments:
            upload_destination: image_fs
            namer:              vich_uploader.namer_uniqid
            delete_on_remove:   true
        post_image:
            upload_destination: image_fs
            namer:              vich_uploader.namer_uniqid
            delete_on_remove:   true
```

```
// services.yml
    jp.s3_client:
            class: Aws\S3\S3Client
            factory_class: Aws\S3\S3Client
            factory_method: factory
            arguments:
                - ["KEY", "SECRET"]
```

I'm testing this on my development machine, which is unfortunately rather slow. But I don't know if this error is because of the actual timeout (so that the connecting part took too long), or if there's an  error in my configuration.

Thanks in advance
