### ISSUE TITLE
Database field not updating

### ISSUE THREAD

**Issue by MHaendel** [dustin10/VichUploaderBundle#365]
Hey,

once I uploaded a file, it doesn't get set in the database. I use FOSUserBundle and modified to ProfileFormType. I want to update the avatarFile / avatar.

This is my config:

``` yaml
vich_uploader:
    db_driver: orm
    storage: file_system
    twig: true
    mappings:
        user_avatar:
            uri_prefix:         /images/avatars
            upload_destination: %kernel.root_dir%/../web/images/avatars
            delete_on_remove: true
            delete_on_update: true
            inject_on_load: true
        user_cover:
            uri_prefix:         /images/covers
            upload_destination: %kernel.root_dir%/../web/images/covers
```

This is my Entity:

``` php
<?php

namespace EdelNetzwerk\UserBundle\Entity;

use FOS\UserBundle\Model\User as BaseUser;
use Doctrine\ORM\Mapping as ORM;
use FOS\MessageBundle\Model\ParticipantInterface;
use Symfony\Component\HttpFoundation\File\File;
use Vich\UploaderBundle\Mapping\Annotation as Vich;
use Symfony\Component\Validator\Constraints as Assert;



/**
 * User
 *
 * @ORM\Table(name="fos_user")
 * @ORM\Entity
 * @Vich\Uploadable
 */
class User extends BaseUser implements ParticipantInterface
{
    /**
     * @var integer
     *
     * @ORM\Column(name="id", type="integer")
     * @ORM\Id
     * @ORM\GeneratedValue(strategy="IDENTITY")
     */
    protected $id;

    /**
     * @ORM\Column(type="datetime")
     *
     * @var \DateTime $updatedAt
     */
    protected $updatedAt;


    /**
     * @Assert\Image(
     *      maxSize="2M",
     *      mimeTypes={"image/png", "image/jpeg", "image/pjpeg"}
     * )
     * @Vich\UploadableField(mapping="user_avatar", fileNameProperty="avatar", nullable=true)
     *
     * @var File $avatarFile
     */
    protected $avatarFile;

    /**
     * @var string
     * 
     * @ORM\Column(name="avatar", type="string", length=255, nullable=true)
     */
    protected $avatar;



    /**
     * Gets the value of id.
     *
     * @return integer
     */
    public function getId()
    {
        return $this->id;
    }

    /**
     * Sets the value of id.
     *
     * @param integer $id the id
     *
     * @return self
     */
    protected function setId($id)
    {
        $this->id = $id;

        return $this;
    }


    public function setAvatarFile($avatarFile)
    {
        $this->avatarFile = $avatarFile;

        if ($avatarFile) {
            // It is required that at least one field changes if you are using doctrine
            // otherwise the event listeners won't be called and the file is lost
            $this->setUpdatedAt(new \DateTime());
        }

        return $this;
    }

    /**
     * @return File
     */
    public function getAvatarFile()
    {
        return $this->avatarFile;
    }

    /**
     * @param string $avatar
     */
    public function setAvatar($avatar)
    {
        $this->avatar = $avatar;

        return $this;
    }

    /**
     * @return string
     */
    public function getAvatar()
    {
        return $this->avatar;
    }

    /**
     * Gets the value of updatedAt.
     *
     * @return \DateTime $updatedAt
     */
    public function getUpdatedAt()
    {
        return $this->updatedAt;
    }

    /**
     * Sets the value of updatedAt.
     *
     * @param \DateTime $updatedAt $updatedAt the updated at
     *
     * @return self
     */
    protected function setUpdatedAt($updatedAt)
    {
        $this->updatedAt = $updatedAt;

        return $this;
    }
}

```
