### ISSUE TITLE
Listener events never called

### ISSUE THREAD

**Issue by khepin** [dustin10/VichUploaderBundle#46]
Just tried updating to symfony 2.1, I also probably was a little bit behind on this bundle, so there seemed to be one difference in config: `upload_dir` replaced by `upload_destination`.

However it seems that now the listener events are never called. I changed all the listener functions to just `die('listener called')` but this never seems to be triggered.

My config now reads:

```
vich_uploader:
    db_driver: mongodb
    storage: vich_uploader.storage.file_system
    mappings:
        league_thumbnail:
            upload_destination: %kernel.root_dir%/../web/uploads/leagues/photos
            namer: mashup.upload_namer
            inject_on_load: false
        # ...
```

Any ideas why this is happening?
