### ISSUE TITLE
Entity update and required form field

### ISSUE THREAD

**Issue by andrewlakomski** [dustin10/VichUploaderBundle#468]
Hi,

I've encountered a problem with entity update using this bundle.
HTML5 validation throws required field error when there is already uploaded file.

Mappings:

Config:

``` yml
vich_uploader:
    db_driver: orm

    mappings:
         foo_image:
            uri_prefix: /uploads/foo
            upload_destination: %kernel.root_dir%/../web/uploads/foo
```

Entity:

``` yml
FooBundle\Entity\Foo:
    type: entity
    table: null
    id:
        id:
            type: integer
            generator:
                strategy: AUTO
    fields:
        image:
            type: string
            length: 255

    lifecycleCallbacks: {  }
```

Vich:

``` yml
FooBundle\Entity\Foo:
    imageFile:
        mapping: foo_image
        filename_property: image
```

``` php
<?php

namespace FooBundle\Entity;

use Symfony\Component\HttpFoundation\File\UploadedFile;

class Foo
{
    /**
     * @var int
     */
    private $id;

    /**
     * @var string
     */
    private $image;

    /**
     * @var UploadedFile
     */
    private $imageFile;

    /**
     * @return int
     */
    public function getId()
    {
        return $this->id;
    }

    /**
     * @param int $id
     *
     * @return Foo
     */
    public function setId($id)
    {
        $this->id = $id;

        return $this;
    }

    /**
     * @return string
     */
    public function getImage()
    {
        return $this->image;
    }

    /**
     * @param string $image
     *
     * @return Foo
     */
    public function setImage($image)
    {
        $this->image = $image;

        return $this;
    }

    /**
     * @return UploadedFile
     */
    public function getImageFile()
    {
        return $this->imageFile;
    }

    /**
     * @param UploadedFile $imageFile
     *
     * @return Foo
     */
    public function setImageFile($imageFile)
    {
        $this->imageFile = $imageFile;

        return $this;
    }
}
```

Form

``` php
<?php

namespace FooBundle\Form;

use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolverInterface;

class FooType extends AbstractType
{
    /**
     * @param FormBuilderInterface $builder
     * @param array                $options
     */
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder
            ->add(
                'imageFile',
                'vich_image',
                [
                    'label'    => 'Image'
                ]
            );
    }

    /**
     * @param OptionsResolverInterface $resolver
     */
    public function setDefaultOptions(OptionsResolverInterface $resolver)
    {
        $resolver->setDefaults(
            [
                'data_class' => 'FooBundle\Entity\Foo'
            ]
        );
    }

    /**
     * @return string
     */
    public function getName()
    {
        return foobundle_foo';
    }
}

```

Upload work's fine on create entity, but when I add 

``` php
'required' => true
```

to form and try to edit entity I can't submit form due to validation error.
