### ISSUE TITLE
vich_uploader.namer_property not working

### ISSUE THREAD

**Issue by apfz** [dustin10/VichUploaderBundle#472]
In the documentation it is said that you can use 3 different kinds of namers:

https://github.com/dustin10/VichUploaderBundle/blob/master/Resources/doc/namers.md

vich_uploader.namer_uniqid
vich_uploader.namer_origname
vich_uploader.namer_property

When trying the namer_property i am getting the following error:

Invalid type for path "vich_uploader.mappings.profile_image.namer". Expected scalar, but got array

The config looks like this (as suggested in the documentation)

```yml
    mappings:    
        profile_image:
            uri_prefix:         /uploads/images
            upload_destination: %kernel.root_dir%/data/uploads/images
            namer:
                service: vich_uploader.namer_property
                options: { property: 'categoryId'}
```

Any idea why this is so?
