### ISSUE TITLE
Service not found.

### ISSUE THREAD

**Issue by theantichris** [dustin10/VichUploaderBundle#482]
I've installed and implemented the basic usage of the bundle and that works great.

Now I'm trying to implement the vich_uploader.namer_uniquid service.

```
vich_uploader:
  db_driver: orm
  mappings:
    page_attachment:
      uri_prefix: /uploads/page
      upload_destination: %kernel.root_dir%/../web/uploads/page
      namer: vich_uploader.namer_uniquid
```

I'm getting a 500 error because it cannot find the server.

You have requested a non-existent service "vich_uploader.namer_uniquid".
