### ISSUE TITLE
configured mapping uploads to local fs instead of s3

### ISSUE THREAD

**Issue by poulping** [dustin10/VichUploaderBundle#496]
Hello,
I am using VichUploaderBundle with flysystem to manage uploads locally and to s3. Locally it works great, when I want to upload to s3 it uploads locally under the web directory, without an error. 
I would expect either a config error, or the file to be uploaded to s3 correctly.
I can't really figure out what I do wrong...

My mappings are defined as follow:
```yaml
oneup_flysystem:
  adapters:
    user_background:
      local:
        directory: %kernel.root_dir%/../web/uploads/user/background
    archive_adapter:
      awss3v3:
        client: birdfeed.s3.client
        bucket: myBucket
        prefix: /myprefix



  filesystems:
    user_background_fs:
      adapter:    user_background
      mount:      user_background_fs
    asset_archive_fs:
      adapter: archive_adapter
      mount:   asset_archive_fs

vich_uploader:
  db_driver: orm
  mappings:
    user_background:
      uri_prefix: /uploads/user/background
      upload_destination: user_background_fs
    asset:
      upload_destination: asset_archive_fs
```

the dependent service is configured too:
```yaml
birdfeed.s3.client:
    class: Aws\S3\S3Client
    factory_class: Aws\S3\S3Client
    factory_method: factory
    arguments:
      -
        version: 'latest'
        region: 'us-east-1'
        key: "mykey"
        secret: "mysecret"
```

and finally the config in my entity:

```php
/**
 * Class LocalProduct
 * @package BirdFeed\WebSiteBundle\Entity
 * @ORM\Entity
 * @ORM\HasLifecycleCallbacks
 * @Vich\Uploadable
 */
class LocalProduct extends Product
{
    const TYPE = self::TYPE_LOCAL;
    /**
     * @Assert\File()
     * @Vich\UploadableField(mapping="asset", fileNameProperty="archive")
     * @var File archiveFile
     */
    protected $archiveFile;

```

what am I missing?

Thanks!
