### ISSUE TITLE
Property Namer

### ISSUE THREAD

**Issue by fcpauldiaz** [dustin10/VichUploaderBundle#512]
I'm trying to use a namer with a custom property like this:

```yaml
vich_uploader:
    # ...
    mappings:
        product_image:
            upload_destination: product_image_fs
            namer:
                service: vich_uploader.namer_property
                options: { property: 'slug'} # supposing that the object contains a "slug" attribute or a "getSlug" method
```

But I'm getting this error with Symfony 2.7.8

```
[Symfony\Component\Config\Definition\Exception\InvalidTypeException]         
  Invalid type for path "vich_uploader.mappings.document.namer". Expected sca  
  lar, but got array.  
```
