### ISSUE TITLE
Using different db drivers for different mappings

### ISSUE THREAD

**Issue by samasq** [dustin10/VichUploaderBundle#516]
Can anyone suggest a solution? In my app I am using phpcr for a cmf component alongside Doctrine ORM for realtional tables of product data. This segregated approach is recommended in the symfony documentation as PHPCR is not suitable for relational data whereas an ORM is not suitable for storing hierarchical data.

However I cant seem to tell vich uploader to use the separate drivers for separate mappings. One works fine when I set either phpcr or orm, but then the other doesnt work at all. Vich just doesnt move the uploaded file and throws no error.

Is it possible to use different drivers in each file mapping? Here are my current mappings. I have tried moving the db_driver parameter into the mappings but then vich throws an error saying the db driver param must be set.

```
vich_uploader:
    db_driver: phpcr
    storage: file_system
    mappings:
        product_image:
            uri_prefix:         /images/product
            upload_destination: %kernel.root_dir%/../web/assets/images/product
            inject_on_load:     true
            delete_on_update:   true
            delete_on_remove:   true
        blog_post_image:
            uri_prefix:         /images/blog
            upload_destination: %kernel.root_dir%/../web/assets/images/blog
            inject_on_load:     true
            delete_on_update:   true
            delete_on_remove:   true
```
Thanks for any help or info

**Comment by K-Phoen** [comment]
The following should be possible:

```yaml
vich_uploader:
    db_driver: phpcr # default driver
    storage:   file_system
    mappings:
        product_image:
            uri_prefix:         /images/product
            upload_destination: %kernel.root_dir%/../web/assets/images/product
            inject_on_load:     true
            delete_on_update:   true
            delete_on_remove:   true
            db_driver:          orm # overriden driver
        blog_post_image:
            uri_prefix:         /images/blog
            upload_destination: %kernel.root_dir%/../web/assets/images/blog
            inject_on_load:     true
            delete_on_update:   true
            delete_on_remove:   true
```
