### ISSUE TITLE
jpegPhoto doesn't trigger desired accessor

### ISSUE THREAD

**Issue by Dragnucs** [dustin10/VichUploaderBundle#542]
If I set my config like this:
```yaml
fr3d_ldap:
    user:
        attributes:
            - { ldap_attr: jpegPhoto, user_method: setJpegPhoto }
```
Then `setJpegPhoto()` method is never called. Other methods are called just fine.
