### ISSUE TITLE
[Symfony2] Display and download files in folder outside web ? 

### ISSUE THREAD

**Issue by xzks** [dustin10/VichUploaderBundle#565]
Hello,

I placed my files outside of web folder for more secure. And the users can't access it to view and download. It's normal.
But how to recover my files for view or download ? The path ?
I try to implement a function in my controller but I don't know how to use with VichUploaderBundle.
Besides, if I use it in my twig, I have a probleme of path.
`<img src="{{ vich_uploader_asset(product, 'image') }}" alt="{{ product.name }}" />` 

Here my controller:

```
public function downloadImageAction(Image $image)
    {
        $downloadHandler = $this->get('vich_uploader.download_handler');

        return $downloadHandler->downloadObject($image, $fileField = 'imageFile');
    }
```

    /* Controller action for file download link */
    public function getFileAction($filename)
    {
        $path = $this->container->getParameter('dir_my_files');
        $myFile = $path . $filename;

        $content = file_get_contents($myFile);
        $response = new Response();
        $response->headers->set('Content-Type', 'text/csv');
        $response->headers->set('Content-Disposition', 'attachment;filename="'.$filename);
        $response->setContent($content);

        return $response;
    } 

Here my config.yml:

```
vich_uploader:
    db_driver: orm
    mappings:
        copyrightHolder_iban:
            uri_prefix: images/iban_copyrightHolders
            upload_destination: %kernel.root_dir%/../uploads/images/iban_copyrightHolders
            namer: vich_uploader.namer_origname
            inject_on_load: false
            delete_on_update: true
            delete_on_remove: true
```

And my twig:

```
<button type="button" class="btn btn-theme01">
<a href="{{ vich_uploader_asset(copyrightHolder, 'ibanFile') }}" download="iban_{{ copyrightHolder.firstName ~ "_" ~ copyrightHolder.lastName }}" >{{ 'Download'|trans }}</a>
</button>
```

I hope I have enough detail to you understand my problem.

Thanks,
