### ISSUE TITLE
Relative URL in twig template

### ISSUE THREAD

**Issue by appyapp** [dustin10/VichUploaderBundle#571]
Hi everyone,

I guess I'm doing something wrong but can't figure what. This my config :

```
vich_uploader:
    db_driver: orm
    twig: true
    mappings:
        race_image:
            uri_prefix: uploads/images/races
            upload_destination: %kernel.root_dir%/../web/uploads/images/races
            namer:
                service: vich_uploader.namer_property
                options: {property: 'slug'}
            inject_on_load: true
            delete_on_update: true
            delete_on_remove: true

        race_tour:
            uri_prefix: uploads/tours
            upload_destination: %kernel.root_dir%/../web/uploads/tours
            namer:
                service: vich_uploader.namer_property
                options: {property: 'title' }

            inject_on_load: true
            delete_on_update: true
            delete_on_remove: true

        user_image:
            uri_prefix: uploads/images/users
            upload_destination: %kernel.root_dir%/../web/uploads/images/users
            namer:
                service: vich_uploader.namer_property
                #We could create a custom namer service to change the default namer and use a combination of properties
                options: {property: 'name' }
            inject_on_load: true
            delete_on_update: true
            delete_on_remove: true
```

And in my twig template I do (for race_image) : 
`<img src="{{ vich_uploader_asset(race,'imageFile') }}" alt="{{race.image}}">`

My problem is that the generated url is a relative one :
`uploads/images/races/my_image.jpg`
and it's not resolved by the system.

I use assetic for asset management and so I noticed that I have to embrace the vich_uploader_asset function with asset() function. My problem is resolved but it's not compliant with the documentation...
Does the fact that I'm in localhost impact the way everything work ?

Thanks in advance.
