### ISSUE TITLE
Absolute path

### ISSUE THREAD

**Issue by saturnxxi** [dustin10/VichUploaderBundle#581]
Hello, 

after uploading images, i can see, that all the uploaded files are saved with absolute paths in the database. I thought it should be only the file name. Can i change this?

Thanks

**Comment by QasAshraf** [comment]
I can see this too, using Symfony 3, VichUploaderBundle 1.1.0 and PHP 7.  Have copied in relevant bits of configuration below, hopefully enough information to help diagnose the problem.

````
# app/config/config.yml

# Twig Configuration
twig:
    ...
    form_themes:
        - 'bootstrap_3_layout.html.twig'
        - 'VichUploaderBundle:Form:fields.html.twig'

vich_uploader:
    db_driver: orm

    mappings:
            category_image:
                uri_prefix:         /images/categories
                upload_destination: %kernel.root_dir%/../web/images/categories
                namer:
                                service: vich_uploader.namer_property
                                options: { property: 'name'}
````

````
# src/MyAppBundle/Form/CategoryType.php

    /**
     * @param FormBuilderInterface $builder
     * @param array $options
     */
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder
            ->add('name')
            ->add('image', VichImageType::class, array(
                'required'      => true,
                'property_path' => 'imageFile',
                'allow_delete'  => false
            ));
        ;
    }

````
````
# src/MyAppBundle/Entity/Category.php
/**
     *
     * @Vich\UploadableField
     *
     * @var File
     */
    private $imageFile;


    /**
     * @return File
     */
    public function getImageFile()
    {
        return $this->imageFile;
    }


    /**
     * @param File|\Symfony\Component\HttpFoundation\File\UploadedFile $image
     *
     * @return Category
     */
    public function setImageFile(File $image = null)
    {
        $this->imageFile = $image;

        if ($image)
        {
            $this->updatedAt = new \DateTime('now'); # Hack to make doctrine save record
        }

        return $this;
    }
````
