### ISSUE TITLE
Not usable when entity exists outside bundle

### ISSUE THREAD

**Issue by mwoynarski** [dustin10/VichUploaderBundle#598]
This may be an issue of me missing something in the documentation, rather than a bug - the project I'm working on uses a domain model that places the entity outside of the actual application bundle and uses Doctrine yaml mapping to create the database schema - this means I can't use annotations on the entity itself, but the yaml configuration for the uploader requires the configuration files to be in the same bundle as the entity, which isn't possible either.

Is there any mechanism by which YAML can be used to configure the uploader, with the configuration .yml files in a separate bundle from the mapped entity?

**Comment by garak** [comment]
It should work also with an external entity

**Comment by mwoynarski** [comment]
Right, I'm aware that it works with an external entity; my questions is regarding the configuration when using YAML specifically - is there a way to add the uploader functionality to an entity, without using annotations?

The only way I've been able to accomplish it is to add the VichUploader annotation to the entity directly, which doesn't fit my purposes.

**Comment by garak** [comment]
Well, some docs are missing, but this is currently possible.
For example, if your entity is in the namespace `Acme\Model\Entity`, you can use this:
```yaml
# app/config/vich_uploader
Acme\Model\Entity\User:
    imageFile:
        mapping: image
        filename_property: imageName
```

and use following configuration:
```yaml
# app/config/config.yml
vich_uploader:
    db_driver: orm
    mappings:
        image:
            uri_prefix: /images
            upload_destination: '%kernel.root_dir%/../web/images'
            inject_on_load: true
    metadata:
        auto_detection: false
        directories:
            - {path: '%kernel.root_dir%/config/vich_uploader', namespace_prefix: 'Acme'}
```

I'll upgrade docs
