### ISSUE TITLE
How to resize image size when upload?

### ISSUE THREAD

**Issue by winds1983** [dustin10/VichUploaderBundle#605]
Now I use VichUploaderBundle + KnpGaufretteBundle to upload image to AWS s3, but how to resize image size when upload?

**Comment by Dragnucs** [comment]
Use an event listener and subsbscribe to the event `PostUpload'.

You get the metadata like destination directory from `$event->getMapping()` and the file from `$event->getObject()`.

**Comment by winds1983** [comment]
@Dragnucs Ok, Thanks.

**Comment by AienTech** [comment]
I've created the event listener (Please update events documentation if you can) but it's not dispatched...

```
    admin.event.vich_uploader_post_upload:
        class: Administration\SystemBundle\EventListener\VichImageHandling
        tags:
            - { name: kernel.event_listener, event: vich_uploader.PostUpload , method: resizeImage }
```
```
namespace Administration\SystemBundle\EventListener;

use Symfony\Component\HttpKernel\HttpKernel;
use Vich\UploaderBundle\Event\Event;

class VichImageHandling
{
    public function resizeImage(Event $event)
    {
        $uploadedFile = $event->getObject();
        dump($uploadedFile);
        return null;
    }
}
```

is there anything I'm missing?
