### ISSUE TITLE
Problem with User in FOSUserBundle

### ISSUE THREAD

**Issue by Chrysweel** [dustin10/VichUploaderBundle#63]
Hello.
I have a field image in my entity User.php

But when I want edit my email with FOsUserBundle I got the error:

The file is not found.

My field image into User entity is:

```
/**
     * @ORM\Column(type="string", length=255, name="image_name", nullable=true)
     */
    public $imageName;
    /**
     * @Assert\File(
     *     maxSize="200k",
     *     mimeTypes={"image/png", "image/jpeg", "image/pjpeg"}
     * )
     * @Vich\UploadableField(mapping="imagen_perfil", fileNameProperty="imageName")
     *
     * @var File $image
     */
    protected $image;
```

In my config.yml is:

```
vich_uploader:
    db_driver: orm
    gaufrette: false
    storage: vich_uploader.storage.file_system 
    mappings:
        product_image:
            uri_prefix: /workspace/chateagratis/web/uploads/perfil
            upload_destination: %kernel.root_dir%/../web/uploads/fotos 
        imagen_perfil:
            uri_prefix: /workspace/chateagratis/web/uploads/perfil
            upload_destination: %kernel.root_dir%/../web/uploads/perfl
```

Not compatible image field in the user entity with FOSUserBundle?
