### ISSUE TITLE
Serialization of '...File' is not allowed when saving

### ISSUE THREAD

**Issue by schingeldi** [dustin10/VichUploaderBundle#64]
I followed the documentation. But when saving I get the error:

Exception: Serialization of 'Symfony\Component\HttpFoundation\File\File' is not allowed

and 

Exception: Symfony\Component\HttpKernel\DataCollector\RequestDataCollector::serialize() must return a string or NULL

When I remove the VichUploader Assertion

``` php
@Vich\UploadableField(mapping="organization_logo", fileNameProperty="headerLogoName")
```

then everything the error disappears and saving works. That's why I post this problem here. I googled a little bit and found, that other persons having similar problems, but not mentioning this Bundle.

Here are extracts of my code:

``` php
// Entity


    /**
     * @Assert\File(
     *     maxSize="1M",
     *     mimeTypes={"image/png", "image/jpeg", "image/pjpeg"}
     * )
     *@Vich\UploadableField(mapping="organization_logo", fileNameProperty="headerLogoName")
     *
     * @var File $image
     */
    protected $headerLogo;

    /**
     * @ORM\Column(type="string", length=255, name="header_logo_name")
     *
     * @var string $headerLogoName
     */
    protected $headerLogoName;



// form

$builder->add('headerLogoName', 'file');

```

``` yml

# config
knp_gaufrette:
    adapters:
        organization_adapter:
            local:
                directory:  %acme.media_dir%/images/organization

    filesystems:
        organization_logo_fs:
            adapter:    organization_adapter


vich_uploader:
    db_driver: orm
    gaufrette: true
    storage: vich_uploader.storage.gaufrette
    mappings:
        organization_logo:
            uri_prefix: /images/organization/logo/
            upload_destination: organization_logo_fs
```

Thanks for any helps and thoughts
