### ISSUE TITLE
Clone an entity with uploadable file

### ISSUE THREAD

**Issue by roberto910907** [dustin10/VichUploaderBundle#682]
Im trying to clone an entity with a property imagenFile and a configuration like this:

Novedad Entity:
```
     /**
     * NOTE: This is not a mapped field of entity metadata, just a simple property.
     *
     * @Vich\UploadableField(mapping="adjunto_novedad", fileNameProperty="imagenName")
     *
     * @var File $imagenFile
     */
    protected $imagenFile;
```

app/config.yml:
```
adjunto_novedad:
        uri_prefix: /uploads
        upload_destination: '%kernel.root_dir%/../web/uploads'
        directory_namer:
            service: mysoft.directory_namer_subdir
            options: { user_relation: true, method: getUsuario, upload_to: /novedad_adjunto }
```

My code:
 ```
            /* @var Novedad $novedad */
            $novedad = $this->form->getData();
            $usuarios = $this->request->request->get('novedad')['usuario'];

            foreach ($usuarios as $usuario_id) {
                $trabajador = $this->trabajador_manager->findTrabajadorById($usuario_id);

                $novedad_trabajador = clone $novedad;
                $novedad_trabajador->setUsuario($trabajador);
                $this->novedad_manager->updateNovedad($novedad_trabajador);
            }
```

The issue is that the second object throw an error saying:
The file "risa.jpg" was not uploaded due to an unknown error. 500 Internal Server Error - FileException

This is the image of the coincidence between both object cloned:
![imagen_error](https://cloud.githubusercontent.com/assets/12180771/23820065/6d387054-05de-11e7-88ea-75dd268aec8d.png)

And the issue:
![imagen_error2](https://cloud.githubusercontent.com/assets/12180771/23820076/a91bad20-05de-11e7-8ed7-870219c584cd.png)

With the first object everything its ok, but the second clone object throw the error.

Any help it would be appreciated.
