### ISSUE TITLE
Absolute URL to File

### ISSUE THREAD

**Issue by dustin10** [dustin10/VichUploaderBundle#7]
Implement a way to get an absolute URL to a file.

**Comment by loostro** [comment]
@patrickli thanks, `{{ app.request.getUriForPath(vich_uploader_asset(entity, 'file_name')) }}` this is perfect

**Comment by TomaszKotlarek** [comment]
```
#config.yml
framework:
    assets:
        base_urls: ['http://example.com']
```

```
{# template #}
{{ asset(vich_uploader_asset(event, 'fileLogo')) }}
```

That gives me http://example.com/path/to/asset/0123_456.jpg
