### ISSUE TITLE
inject_on_load configuration injects all fields when at least one is true

### ISSUE THREAD

**Issue by ericmgoeken** [dustin10/VichUploaderBundle#717]
If some mappings have inject_on_load set to false, but others are set to true. It will ignore the ones that are marked false and inject them all. 

```
# app/config/config.yml
vich_uploader:
    mappings:
        product_image:
            ...
            inject_on_load: false 
        product_video:
            ...
            inject_on_load: true
```
