### ISSUE TITLE
Cannot override widgets via config option since 1.6.0

### ISSUE THREAD

**Issue by Danita** [dustin10/VichUploaderBundle#733]
Hi! We had the following configuration on 1.5.3

```yml
# Twig Configuration
twig:
    form_themes:
        - VichUploaderBundle:Form:fields.html.twig
        - AppBundle:Overrides:form.html.twig
```

In which we overrode some widgets in `AppBundle:Overrides:form.html.twig` like so:

```twig
{% block vich_file_widget %}
    <div class="input-group">
      <span class="input-group-btn">
        <span class="btn btn-success btn-file">
          Seleccionar&hellip;
          {{ form_widget(form.file)}}
        </span>
      </span>
      <input type="text" class="form-control" readonly />
    </div>
    {# etc.. #}
{% endblock %}
```
But this is not working since 1.6.0, the library is completely ignoring our template.

One workaround we found is to add an empty `app/Resources/VichUploaderBundle/views/Form/fields.html.twig`. In that case, the overrides work again.

Any ideas?
