### ISSUE TITLE
The file extension is not registered

### ISSUE THREAD

**Issue by christophe-44-27** [dustin10/VichUploaderBundle#761]
Hi, 

I have a problem with the namer and the uploaded file. I've chosen the following namer :
        tutorial_cover:
            uri_prefix:         /img/uploads/users/tutorials
            upload_destination: '%tutorial_directory%'
            namer:              **vich_uploader.namer_origname**

So, if i refer to the documentation, i have to retrieve the extension file on the uploaded file and there is not. I only have the name "598cc92d22689_598cc92d1def6"

Is it normal ?

Regards,
Christophe

**Comment by garak** [comment]
Is ""598cc92d22689_598cc92d1def6" the original name of the file you uploaded? If not, there's something wrong with configuration.
You can check your current config using `bin/console debug:conf vich_uploader`

**Comment by christophe-44-27** [comment]
Hi,
The original name is : 598cc92d1def6.jpg so the namer works for the "beginning because it's does a sort of "concatenation" of the name and the uniqid but it's not registered the extension file.

```
Current configuration for extension with alias "vich_uploader"
==============================================================

vich_uploader:
    db_driver: orm
    mappings:
        tutorial_cover:
            uri_prefix: /img/uploads/users/tutorials
            upload_destination: /Users/****/Sites/***/app/../web/img/uploads/users/tutorials
            namer:
                service: vich_uploader.namer_origname
                options: {  }
            directory_namer:
                service: null
                options: null
            delete_on_remove: true
            delete_on_update: true
            inject_on_load: false
            db_driver: null        
    default_filename_attribute_suffix: _name
    storage: file_system
    twig: true
    metadata:
        cache: file
        file_cache:
            dir: /Users/*****/Sites/******i/var/cache/dev/vich_uploader
        auto_detection: true
        directories: {  }
```
I don't understand what happened :(
