### ISSUE TITLE
Proper configuration of mapping in YAML

### ISSUE THREAD

**Issue by stirith** [dustin10/VichUploaderBundle#773]
I made everything what was wrote in https://github.com/dustin10/VichUploaderBundle/blob/master/Resources/doc/usage.md 
and
https://github.com/dustin10/VichUploaderBundle/blob/master/Resources/doc/mapping/yaml.md

Now problem which I have is that when I try update object (Product) (doctrine:generate:entities) and update database any fields related to file are not adding. Unfortunately in documentation I didn't find information whether Vich...create fields in object (Product) automatically or I should do it manually?

My configuration: config.yml
```yaml
vich_uploader:
    db_driver: orm # or mongodb or propel or phpcr
    mappings:
        product_image:
            uri_prefix:         /images/file
            upload_destination: '%kernel.root_dir%/../web/images/file
```
Product.yml
```yaml
Test\MyBundle\Entity\Product:
    file:
        mapping:           product_image # required
        filename_property: image     # required
```
