### ISSUE TITLE
Deprecated private service in Symfony 3.4

### ISSUE THREAD

**Issue by TeLiXj** [dustin10/VichUploaderBundle#784]
Hi! I have this deprecation message in Symfony 3.4 beta 2 when using vich_uploader_asset twig function to get a user avatar

`User Deprecated: The "vich_uploader.namer_hash.avatar" service is private, getting it from the container is deprecated since Symfony 3.2 and will fail in 4.0. You should either make the service public, or stop using the container directly and use dependency injection instead.`

Regards

**Comment by garak** [comment]
Currently, there's no plan to support Symfony 4.0 yet.

**Comment by garak** [comment]
@TeLiXj try using `^1.7@dev`, deprecations should be gone

**Comment by TeLiXj** [comment]
All works fine, thanks!!!
will we have the final version 1.7 soon?

**Comment by garak** [comment]
I guess that we can wait until Symfony 3.4/4.0 is released, then go with 1.7

**Comment by abastien** [comment]
Hi, if you don't have PHP ^7.0 you are stuck with the 1.4.2 version.
To render the service public just insert the following lines into your app/config/services.yml file.

```
# app/config/services.yml

    vich_uploader.namer_uniqid.user_avatar:
        class: Vich\UploaderBundle\Naming\UniqidNamer
        public: true
```
Enjoy
