### ISSUE TITLE
VichUploaderBundle + OneupFlysystemBundle

### ISSUE THREAD

**Issue by dorcyv** [dustin10/VichUploaderBundle#798]
Hi,
I try to use the `OneupFlysystemBundle` with the Google Cloud Storage adapter.
VichUploaderBundle upload the file on Google Cloud Storage (via the flysystem).
But, when I try to generate the url via the `UploaderHelper` class, it generate a local url and not the google cloud storage url.
Is it a normal behavior ?

The config file:
```
vich_uploader:
    db_driver: orm
    storage: flysystem
    mappings:
        image:
            upload_destination: upload_fs

oneup_flysystem:
    adapters:
        upload_adapter:
            googlecloudstorage:
                client: google_storage_client
                bucket: google_storage_bucket
    filesystems:
        upload_fs:
            adapter:    upload_adapter
            mount:      upload_fs
```

The service file:
```
    google_storage_client:
        class: Google\Cloud\Storage\StorageClient
        arguments:
            - projectId: 'project-id'
              keyFilePath: 'key.json'

    google_storage_bucket:
        class: Google\Cloud\Storage\Bucket
        factory: 'google_storage_client:bucket'
        arguments:
            $name: 'bucketName'

```
