### ISSUE TITLE
Deprecations 

### ISSUE THREAD

**Issue by Sydney-o9** [dustin10/VichUploaderBundle#808]
Hi Team,

I've noticed 1 deprecation in VichUploaderBundle.

> User Deprecated: The "app.storage.vich_uploader.directory_namer.profile" service is private, getting it from the container is deprecated since Symfony 3.2 and will fail in 4.0. You should either make the service public, or stop using the container directly and use dependency injection instead.

```
{▼
  /...../vendor/symfony/dependency-injection/Container.php:275 {▶}
  /...../vendor/vich/uploader-bundle/Mapping/PropertyMappingFactory.php:171 {▼
    › $namerConfig = $config['directory_namer'];
    › $namer = $this->container->get($namerConfig['service']);
    › 
  }
```

This seems to come from the configuration which in `PropertyMappingFactory` is being injected using the container.

Here is an example:
```
vich_uploader:
    db_driver: orm
    storage:   gaufrette

    mappings:
        profile_img:
            # ...
            directory_namer: app.storage.vich_uploader.directory_namer.profile
```
