### ISSUE TITLE
File not uploaded

### ISSUE THREAD

**Issue by antondachauer** [dustin10/VichUploaderBundle#819]
Hi, I'm implementing the bundle in a current project, but the file cannot be uploaded.

Entity (I use yaml mapping):
```
/**
 * @ORM\Entity
 * @Vich\Uploadable
 */
class Image
{

    /**
     * @Vich\UploadableField(mapping="image_mapping", fileNameProperty="path", size="size", mimeType="mimetype", originalName="name")
     *
     * @var File
     */
    private $imageFile;

    public function getImageFile() {
        return $this->imageFile;
    }

    public function setImageFile(UploadedFile $file) {
        $this->imageFile = $file;
    }
```

Bundle config
```
    vich_uploader:
        db_driver: orm
        mappings:
            image_mapping:
                uri_prefix: /images
                upload_destination: '%images.upload_dir%'
                inject_on_load: false
                delete_on_update: true
                delete_on_remove: true

```

Whats wrong?
