### ISSUE TITLE
Custom namer broken in SF 3.4

### ISSUE THREAD

**Issue by binarious** [dustin10/VichUploaderBundle#824]
config.yml:
```yml
vich_uploader:
    db_driver: orm
    mappings:
        issue_documents:
            uri_prefix: /documents/issue
            namer:
                service: my.upload_namer
            upload_destination: "%appdata_path%/documents/issue"
            inject_on_load: true
            delete_on_update: true
            delete_on_remove: true
```
services.yml:
```yml
my.upload_namer:
    class: 'AppBundle\Service\UploadNamer'
    public: true
```

Exception while clearing the cache:
```
$ bin/console cache:clear -vvv

In ResolveChildDefinitionsPass.php line 71:

  [Symfony\Component\DependencyInjection\Exception\RuntimeException]
  Service "my.upload_namer.issue_documents": Parent definition "my.upload_namer" does not exist.


Exception trace:
 Symfony\Component\DependencyInjection\Compiler\ResolveChildDefinitionsPass->doResolveDefinition() at /Users/myuser/projects/myapp/vendor/symfony/symfony/src/Symfony/Component/DependencyInjection/Compiler/ResolveChildDefinitionsPass.php:58
 Symfony\Component\DependencyInjection\Compiler\ResolveChildDefinitionsPass->resolveDefinition() at /Users/myuser/projects/myapp/vendor/symfony/symfony/src/Symfony/Component/DependencyInjection/Compiler/ResolveChildDefinitionsPass.php:39
 Symfony\Component\DependencyInjection\Compiler\ResolveChildDefinitionsPass->processValue() at /Users/myuser/projects/myapp/vendor/symfony/symfony/src/Symfony/Component/DependencyInjection/Compiler/AbstractRecursivePass.php:60
 Symfony\Component\DependencyInjection\Compiler\AbstractRecursivePass->processValue() at /Users/myuser/projects/myapp/vendor/symfony/symfony/src/Symfony/Component/DependencyInjection/Compiler/ResolveChildDefinitionsPass.php:31
 Symfony\Component\DependencyInjection\Compiler\ResolveChildDefinitionsPass->processValue() at /Users/myuser/projects/myapp/vendor/symfony/symfony/src/Symfony/Component/DependencyInjection/Compiler/AbstractRecursivePass.php:39
 Symfony\Component\DependencyInjection\Compiler\AbstractRecursivePass->process() at /Users/myuser/projects/myapp/vendor/symfony/symfony/src/Symfony/Component/DependencyInjection/Compiler/Compiler.php:141
 Symfony\Component\DependencyInjection\Compiler\Compiler->compile() at /Users/myuser/projects/myapp/vendor/symfony/symfony/src/Symfony/Component/DependencyInjection/ContainerBuilder.php:753
 Symfony\Component\DependencyInjection\ContainerBuilder->compile() at /Users/myuser/projects/myapp/vendor/symfony/symfony/src/Symfony/Component/HttpKernel/Kernel.php:634
 Symfony\Component\HttpKernel\Kernel->initializeContainer() at /Users/myuser/projects/myapp/app/AppKernel.php:76
 AppKernel->initializeContainer() at /Users/myuser/projects/myapp/vendor/symfony/symfony/src/Symfony/Component/HttpKernel/Kernel.php:137
 Symfony\Component\HttpKernel\Kernel->boot() at /Users/myuser/projects/myapp/vendor/symfony/symfony/src/Symfony/Bundle/FrameworkBundle/Console/Application.php:63
 Symfony\Bundle\FrameworkBundle\Console\Application->doRun() at /Users/myuser/projects/myapp/vendor/symfony/symfony/src/Symfony/Component/Console/Application.php:148
 Symfony\Component\Console\Application->run() at /Users/myuser/projects/myapp/bin/console:27
```

Symfony: 3.4.3
VichUploadBundle: 1.8.1

Any ideas?
