### ISSUE TITLE
Confused with Gaufrette storage

### ISSUE THREAD

**Issue by aderuwe** [dustin10/VichUploaderBundle#83]
I seem to be somewhat confused about how to use this bundle with Gaufrette. When I have a `local` Gaufrette adapter (inside web folder) and an associated filesystem configured to use with this bundle, things work fine, as the Twig helper generates the URI correctly.

When I move the `local` Gaufrette adapter outside of the web folder, I get 404's as the Twig helper still generates the same URI that I specified in my config relative to the web folder.

When I use instead the `safe_local` Gaufrette adapter even inside of the web folder, things break as the Twig helper still generates the same URI that I specified in my config relative to the web folder, but because of using `safe_local` the Gaufrette id's are now encoded.

I must be doing something terribly wrong here, as it seems this way things can only work with the `local` Gaufrette adapter.
Perhaps it's related to my not quite understanding the DirectoryNamerInterface - I can only get it to work like this:

```
public function directoryName($obj, $field, $uploadDir)
{
    // TODO: figure out the point of this...
    return $uploadDir;
}
```

My working configuration looks like this:

```
# Gaufrette Configuration
knp_gaufrette:
    adapters:
        prize_overlay_image_adapter:
            local:
                directory: %kernel.root_dir%/../web/images/prize/overlay

    filesystems:
        prize_overlay_image_fs:
            adapter: prize_overlay_image_adapter

# VichUploaderBundle Configuration
vich_uploader:
    db_driver: orm
    gaufrette: true
    storage: vich_uploader.storage.gaufrette
    mappings:
        prize_overlay_image:
            uri_prefix: /images/prize/overlay
            upload_destination: prize_overlay_image_fs
            delete_on_remove: true
            delete_on_update: true
            directory_namer: prize_overlay.uploader.gaufrette_namer
```

Any hint as to what I am doing wrong would be greatly appreciated.
