### ISSUE TITLE
"action.delete" translation

### ISSUE THREAD

**Issue by emr** [dustin10/VichUploaderBundle#846]
Why delete label come as "action.delete"?

**Comment by garak** [comment]
Why not?

**Comment by TwentySomething** [comment]
But it's not translating by domain "VichUploaderBundle"

**Comment by garak** [comment]
Currently, the label is ["form.label.delete"](https://github.com/dustin10/VichUploaderBundle/blob/master/Form/Type/VichFileType.php#L65)
The same label is present in [translation files](https://github.com/dustin10/VichUploaderBundle/tree/master/Resources/translations)

**Comment by TwentySomething** [comment]
Yes! This is my problem.
Why delete label come as "action.delete"?

**Comment by garak** [comment]
I don't know
This bundle is providing such label as "form.label.delete".
Anyway, if you provide the source of a full Symfony project where it's possible to reproduce your issue, I'll be glad to help you

**Comment by TwentySomething** [comment]
Thanks.
Btw, I use the uploader with EasyAdminBundle.

EasyAdmin config
```yaml
easy_admin:
    entities:
        MyEntity:
            class: MyEntity
            form:
                fields:
                    - stuff
                    - property: gallery
                      type: collection
                      type_options:
                          entry_type: MyType
                          by_reference: false
```

MyType
```php
$builder
    // ...
    ->add('imageFile', VichImageType::class)
    // ...
```
