### ISSUE TITLE
Parent definition "...\UniqidNamer" does not exist

### ISSUE THREAD

**Issue by AxelBriche** [dustin10/VichUploaderBundle#848]
```
    mappings:
        car_images:
            uri_prefix: '%cars_images_path%'
            upload_destination: '%kernel.project_dir%/public/%cars_images_path%'
            namer: Vich\UploaderBundle\Naming\UniqidNamer

```
**The error:**
Service "Vich\UploaderBundle\Naming\UniqidNamer.car_images": Parent definition "Vich\UploaderBundle\Naming\UniqidNamer" does not exist.
