### ISSUE TITLE
Cannot create mapping for YML declaration

### ISSUE THREAD

**Issue by indapublic** [dustin10/VichUploaderBundle#861]
| Q                          | A
| -------------------------- | -----
| Bug report?                | yes/no
| Feature request?           | yes/no
| BC Break report?           | yes/no
| Symfony version            | 3.4
| VichUploaderBundle version | 1.8

I have entity **AdminBundle\Entity\TuningPart\TuningPartImage** which described in YML format.

Want to use Vich Uploader for Easyadmin

Tried use this filename _Resources/config/vich_uploader/TuningPart.TuningPartImage.yml_ and _Resources/config/vich_uploader/TuningPartImage.yml_. No difference. Still receiving error `Mapping not found for field "imageFile"`. Tried to create incorrect YML but there is no errors. Seems file hasn't been imported.

**Comment by garak** [comment]
Try to force `directories` in your config

**Comment by Gemorroj** [comment]
@garak can you show example? current documentation (https://github.com/dustin10/VichUploaderBundle/blob/master/Resources/doc/mapping/yaml.md) seems outdated for symfony 4.

**Comment by garak** [comment]
While examples are more old-Symfony oriented, you can use them with Symfony 4 as well. Just adapt your paths

**Comment by Gemorroj** [comment]
> An exception has been thrown during the rendering of a template ("The class "App\Entity\File" is not uploadable. If you use annotations to configure VichUploaderBundle, you probably just forgot to add `@Vich\Uploadable` on top of your entity. If you don't use annotations, check that the configuration files are in the right place. In both cases, clearing the cache can also solve the issue.").

src/Resource/config/vich_uploader/Entity.File.yml:
```yaml
App\Entity\File:
    file:
        mapping:           file
        filename_property: fileName
```

**Comment by Gemorroj** [comment]
see `Vich\UploaderBundle\DependencyInjection\VichUploaderExtension::registerMetadataDirectories` and `Metadata\Driver\FileLocator::findFileForClass` (part of https://github.com/schmittjoh/metadata).

working config:

config/vich_uploader/Entity.File.yml
```yaml
App\Entity\File:
    file:
        mapping:           file
        filename_property: fileName
```
config/packages/vich_uploader.yaml
```yaml
vich_uploader:
    db_driver: orm
    mappings:
        file:
            namer: Vich\UploaderBundle\Naming\UniqidNamer
            # ... my config
    metadata:
        auto_detection: false
        directories:
            - {path: '%kernel.project_dir%/config/vich_uploader', namespace_prefix: 'App'}
```
