### ISSUE TITLE
Unable to find template "VichUploaderBundle:form:fields.html.twig"

### ISSUE THREAD

**Issue by drbeef12** [dustin10/VichUploaderBundle#867]
Hi there,

Im using Symfony 4 + Easyadmin bundle and I've got a problem, not sure if its a bug or not.

What I have done:
easy_admin.yaml

```
easy_admin:
  entities:
    Category:
      class: App\Entity\Category
      list:
          fields: ["id", "name"]

      form:
        fields:
          - "name"
          - "slug"
          - "title"
          - { property: "imageFile", type: "vich_file" }
          - "description"

  design:
    form_theme:   ['VichUploaderBundle:Form:fields.html.twig', 'horizontal']
```

After I added design: form_theme etc.. I wil get this error:
"Unable to find template "VichUploaderBundle:form:fields.html.twig"

What am I doing wrong?
