### ISSUE TITLE
Mappings configurations when uploading multiple files 

### ISSUE THREAD

**Issue by Blqck666** [dustin10/VichUploaderBundle#879]
|    Q        |   A
|------------ | -----
| Version     | x.y.z

### Support Question

im uploading multiple images in one entity i made a configuration like this 

```
parameters:
    app.path.coloriage_images: /web/images/coloriage
    app.path.coloriage_images2: /web/images/coloriage2


coloriage_images:
                    uri_prefix: '%app.path.coloriage_images%'
                    upload_destination:  '%kernel.root_dir%/../web/images/coloriage' 
                    namer:
                        service: vich_uploader.namer_uniqid
coloriage_images2:
                    uri_prefix: '%app.path.coloriage_images%'
                    upload_destination:  '%kernel.root_dir%/../web/images/coloriage2' 
                    namer:
                        service: vich_uploader.namer_uniqid
```

```
/**
     * @ORM\Column(type="string", length=255)
     * @var string
     */
    private $img;

    /**
     * @Vich\UploadableField(mapping="coloriage_images", fileNameProperty="img")
     * @var File
     */

    private $imageFile;


    /**
     * @ORM\Column(type="string", length=255)
     * @var string
     */
    private $img2;

    /**
     * @Vich\UploadableField(mapping="coloriage_images2", fileNameProperty="img2")
     * @var File
     */

    private $imageFile2;
```

and i m still getting this : 

>An exception occurred while executing 'INSERT INTO coloriages (img, img2, name, description, categorie, updated_at, created_at, createdBy) VALUES (?, ?, ?, ?, ?, ?, ?, ?)' with params ["5b290f8d8a7a3.jpg", null, "qsdukhj", "qsdgf", "qsdfg", "2018-06-19 14:13:33", "2018-06-19 14:13:33", null]:
SQLSTATE[23000]: Integrity constraint violation: 1048 Le champ 'img2' ne peut être vide (null)
