### ISSUE TITLE
Problem editing Entity with PropertyDirectoryNamer when the slug depends on a different entity.

### ISSUE THREAD

**Issue by xabitrigo** [dustin10/VichUploaderBundle#885]
### Bug Report

|    Q        |   A
|------------ | ------
| BC Break    | no
| Version     | 1.8.2

#### Summary

I have the following configuration:
```yaml
vich_uploader:
    db_driver: orm

    mappings:
        camera_image:
            uri_prefix: /images/cameras
            upload_destination: '%kernel.project_dir%/public/images/cameras'
            directory_namer:
                service: vich_uploader.namer_directory_property
                options: { property: 'slug', transliterate: true} # supposing that the object contains a "slug" attribute or a "getSlug" method
            inject_on_load: true
            delete_on_update: true
            delete_on_remove: true
```

Then I have a Camera Entity with a ManyToOne relationship to a Spot entity. So the Camera entity has this method:

```
    /**
     * @return string
     */
    public function getSlug(): string
    {
        return $this->getSpot()->getShortName();
    }
```

This gets a string without spaces representing the Spot where this Camera is. If I add a new Camera it all goes well. The image is uploaded to the  `/public/images/cameras/{slug}/` folder and everything works.

#### Current behavior

If I edit a Camera, changing the Spot to which is linked, the getSlug method returns a different string, but the image is not moved. Then I go to the web and the following error is thrown: `SplFileInfo::getSize(): stat failed for /.../public/images/cameras/oia/spotSurf.png`

The image is in the original directory, but a new empty folder with the new slug is created.

#### How to reproduce

I guess this happens when you edit any entity with a relationship where the slug is dinamically generated based on a property from the related entity.

#### Expected behavior

The image is moved. At least it shouldn't crash after you edit it.
