### ISSUE TITLE
Mapping not found for field “xx”

### ISSUE THREAD

**Issue by BBBeta** [dustin10/VichUploaderBundle#896]
I read the VichUploaderBundle [documentation](https://github.com/dustin10/VichUploaderBundle/blob/master/Resources/doc/index.md), and I apply what I learn from it to my code.
But when I try to run it code I get this Exception **Mapping not found for field "logoFile"**.
_Note: I'm using Symfony 4.1, and VichUploaderBundle 1.8_

So here is my code ...

**Configuration**

```
// config/packges/vich_uploader.yaml
vich_uploader:
    db_driver: orm
    mappings:
        company_logo:
            uri_prefix: /uploads/logos
            upload_destination: '%kernel.project_dir%/public/uploads/logos'         
            inject_on_load: false
            delete_on_update: true
            delete_on_remove: true
```

**Entity**
```
namespace App\Entity;

/**
 * @Vich\Uploadable
 */
class Company
{
    // ...

    /*
     * @Vich\UploadableField(mapping="company_logo", fileNameProperty="logo")
     */
    private $logoFile;

    /**
     * @ORM\Column(type="string", length=128, nullable=true, unique=true)
     */
    private $logo;

    // ...
}
```

**Form**
```
class CompanyType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder
               // ...
               ->add('logoFile', VichImageType::class);
    }
}
```
