### ISSUE TITLE
XML Mapping: Serialization of 'SimpleXMLElement' is not allowed

### ISSUE THREAD

**Issue by tentwofour** [dustin10/VichUploaderBundle#914]
### Bug Report

|    Q        |   A
|------------ | ------
| BC Break    | ?
| Version     | 1.8.3
#### Summary

Using the XML mapping, following example at https://github.com/dustin10/VichUploaderBundle/blob/master/Resources/doc/mapping/xml.md, but specifying an attribute "dimensions" throws a serialization error. Removing the dimensions attribute removes the exception. It appears to be a valid attribute, as per: https://github.com/dustin10/VichUploaderBundle/blob/master/Metadata/Driver/XmlDriver.php 

#### Current behavior

Using the XML mapping, following example at https://github.com/dustin10/VichUploaderBundle/blob/master/Resources/doc/mapping/xml.md, but specifying an attribute "dimensions" throws a serialization error.

## Create an entity, using Doctrine embeddable:

```xml
<!-- config/doctrine/Media.orm.xml -->
        <?xml version="1.0" encoding="utf-8"?>
<doctrine-mapping xmlns="http://doctrine-project.org/schemas/orm/doctrine-mapping"
                  xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
                  xsi:schemaLocation="http://doctrine-project.org/schemas/orm/doctrine-mapping http://doctrine-project.org/schemas/orm/doctrine-mapping.xsd">
    <entity name="App\Entity\Media" table="media">
        <id name="id" type="integer" column="id">
            <generator strategy="IDENTITY"/>
        </id>
        <embedded name="file" class="Vich\UploaderBundle\Entity\File" use-column-prefix="false"/>
    </entity>
</doctrine-mapping>
```
## Configure the bundle

```yaml
##config/packages/vich_uploader.yaml
vich_uploader:
    db_driver: orm
    metadata:
        auto_detection: false
        directories:
            - { path: '%kernel.project_dir%/config/vich_uploader', namespace_prefix: 'App'}

    mappings:
        media:
            uri_prefix: /uploads/media
            upload_destination: '%kernel.project_dir%/public/uploads/media'
            namer: Vich\UploaderBundle\Naming\OrignameNamer
            inject_on_load: false
```
## Configure mapping with XML, including the dimensions attribute

```xml 
<!-- config/vich_uploader/Entity.Media.xml -->

<vich_uploader class="Ten24\P3Arch\Entity\Media">
    <field mapping="media" name="file" filename_property="file.name"
           size="file.size" dimensions="file.dimensions" mime_type="file.mimeType" original_name="file.originalName" />
</vich_uploader>
```
## Entity Snippet

```php
<?php

namespace App\Entity;
use Symfony\Component\HttpFoundation\File\File;
use Vich\UploaderBundle\Entity\File as EmbeddedFile;

class Media
{
    /**
     * @var \Vich\UploaderBundle\Entity\File
     */
    private $file;

    /**
     * Not persisted
     * @var \Symfony\Component\HttpFoundation\File\File
     */
    private $uploadedFile;

    public function __construct()
    {
        $this->file = new EmbeddedFile();
    }

...

public function setUploadedFile(?File $file = null): void
    {
        $this->uploadedFile = $file;

        if (null !== $file) {
            // It is required that at least one field changes if you are using doctrine
            // otherwise the event listeners won't be called and the file is lost
            $this->updatedAt = new \DateTimeImmutable();
        }
    }

    public function getUploadedFile(): ?File
    {
        return $this->uploadedFile;
    }

    public function setFile(EmbeddedFile $file)
    {
        $this->file = $file;
    }

    public function getFile(): ?EmbeddedFile
    {
        return $this->file;
    }
}
```

## use vich_uploader_asset twig helper function

```twig
{{ vich_uploader_asset(media, 'file') }} <- Throws exception
```

## Exception stems from https://github.com/dustin10/VichUploaderBundle/blob/master/Metadata/ClassMetadata.php

```php
    public function serialize(): string
    {

var_dump($this->fields);

/*
array(1) {
    ["file"]=>
  array(7) {
        ["mapping"]=>
    string(5) "media"
        ["propertyName"]=>
    string(4) "file"
        ["fileNameProperty"]=>
    string(9) "file.name"
        ["size"]=>
    string(9) "file.size"
        ["mimeType"]=>
    string(13) "file.mimeType"
        ["originalName"]=>
    string(17) "file.originalName"
        ["dimensions"]=>
    object(SimpleXMLElement)#1730 (1) {
    [0]=>
      string(15) "file.dimensions"
    }
  }
}
*/
        return serialize([
            $this->fields,
            parent::serialize(),
        ]);
    }
```

#### Expected behavior

No exception, I suppose? ;)
