### ISSUE TITLE
file being uploaded to another path

### ISSUE THREAD

**Issue by adrielwerlich** [dustin10/VichUploaderBundle#925]
|    Q        |   A
|------------ | -----
| Version     | x.y.z

### Support Question

So I have my mapping going like this ->

```
#services.yaml
app.path.manchete_images: \uploads\images\manchetes

#vich_upoader.yaml
vich_uploader:
    db_driver: orm
    twig: true

    mappings:
        manchete_images:
            uri_prefix:  '%app.path.manchete_images%'     # '%app.path.manchete_images%' #
            upload_destination:  '%kernel.project_dir%/public/uploads/images/manchetes'                  #%app.path.manchete_images%           #'%kernel.root_dir%\..\public\web\uploads\images\manchetes'
            delete_on_remove: true # whether to delete file upon removal of entity
            inject_on_load: true
```

But the result file path is comming like this ` C:\xampp_\tmp\phpF148.tmp ` 

Any help...
