### ISSUE TITLE
How to use custom directory namer

### ISSUE THREAD

**Issue by vittore** [dustin10/VichUploaderBundle#98]
Hi,

I' using a custom directory namer.

Acme/MyBundle/DirectoryNamer.php

```
use Vich\UploaderBundle\Naming\NamerInterface;
/**
 * Namer class.
 */
class DirectoryNamer implements NamerInterface
{
public function directoryName($obj, $field, $uploadDir) {
        $username= $obj->document->user->id;
        return $upload = $uploadDir.'/'.$username;
    }
}
```

services.xml

```
    <services>
        <service id="directory_namer.user_path" class="Acme\MyBundle\Namer\DirectoryNamer">
            <argument>name</argument>
            <argument>namer</argument>
        </service>
    </services>
```

config.yml

```
vich_uploader:
    db_driver: orm
    gaufrette: true
    storage: vich_uploader.storage.gaufrette
    mappings:
        document_file:
            uri_prefix: /files
            upload_destination: document_file_fs
            directory_namer: directory_namer.user_path
            namer: vich_uploader.namer_uniqid
```

With these settings I get:
Fatal error: Class Acme\MyBundle\Namer\DirectoryNamer contains 1 abstract method and must therefore be declared abstract or implement the remaining methods (Vich\UploaderBundle\Naming\NamerInterface::name)

May you help me?

Thanks in advance.
v.
