### ISSUE TITLE
Error 500 in vich_uploader.yaml settings.

### ISSUE THREAD

**Issue by DBarkz** [dustin10/VichUploaderBundle#982]
#### Summary

Hi,

I installed the bundle and configured all of the settings and set up vich in my entity with the instructions provided in your guide. Everything is working perfectly on my local dev version; I go to my entity crud create a new one or edit an existing one and add an image to it and it uploads as expected. However, I am experiencing issues while in production on my host.

#### Current behavior

Whenever I go to create a new entity or edit one whether it is to do with the entity using vich or not I get an error 500 exception. I am using Nginx in production for the first time (I always used Apache in the past), and I have looked through all the error logs and there is nothing in there related to this at all (unless there is an error log I don't know about). So I also tried altering permissions on the folders where the files would be uploaded to via vich which also did not help.  Also on my production server I briefly switched my environment to dev in my .env.local file to see if the problem would persist, and it didn't, everything worked perfectly, but when I switched back to prod the problem started again, so it doesen't seem as though there are any firewall issues. In the end, I completely removed Vich and installed it again, I figured if I went step by step with the same configuration I could find out what the problem was. The problem appears to be quite early on in the set up in the mapping setting in vich_uploader.yaml.

#### How to reproduce

The steps I took were:

- Installed Vich with:

> composer require vich/uploader-bundle

- Added the following code to vich_uploader.yaml:

```
    vich_uploader:
        db_driver: orm

        mappings:
            product_image:
                uri_prefix: /images/products
                upload_destination: '%kernel.project_dir%/public/images/products'
```

- I then deployed to my production server and this is where the problem starts. It appears to be when anything is posted.

#### Expected behavior

File should upload to destination and entity should save without error.

Thanks for any help.
